import { Quiz } from "./types.js";

/**
 * Organik kimyo — Alkanlar (SLAYD-I-3)
 * 60 ta savol 3 ta mustaqil quizga bo'lingan: I3_1, I3_2, I3_3
 * Har bir savolga 20 soniya beriladi. Faqat guruhlarda o'tkaziladi.
 * Har safar savollar va 4 ta javob varianti alohida aralashtiriladi.
 */

export const i3Quiz1: Quiz = {
  id: "I3_1",
  title: "Alkanlar — 1-qism (I3_1)",
  description: "01–20-savollar: Tuzilish, nomlanish va izomeriya (20s/savol)",
  source: "Abdusalom Saidov slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "i3_1_1",
      question: "Alkanlar qanday uglevodorodlar?",
      options: ["Ochiq zanjirli, faqat oddiy bog'larga ega to'yingan uglevodorodlar","Faqat halqali aromatik uglevodorodlar","Uch bog'li to'yinmagan uglevodorodlar","Faqat kislorod saqlovchi birikmalar"],
      correctOptionId: 0,
      explanation: "Slaydda alkanlar ochiq zanjirli va oddiy sigma bog'li birikmalar deb ta'riflangan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_2",
      question: "Ochiq zanjirli alkanlarning umumiy formulasi qaysi?",
      options: ["CnH2n","CnH2n-2","CnH2n+2","CnHn"],
      correctOptionId: 2,
      explanation: "To'yingan ochiq zanjirli uglevodorodlar CnH2n+2 formulasiga mos keladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_3",
      question: "Alkanlarning birinchi vakili qaysi modda?",
      options: ["Etan","Metan","Propan","Butan"],
      correctOptionId: 1,
      explanation: "Metan CH4 — alkanlar gomologik qatorining birinchi a'zosi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_4",
      question: "Metanning molekulyar formulasi qaysi?",
      options: ["C2H6","CH3","C2H4","CH4"],
      correctOptionId: 3,
      explanation: "Metan bir uglerod va to'rt vodorod atomidan iborat.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_5",
      question: "Ketma-ket ikki alkan gomologi tarkibi nimaga farq qiladi?",
      options: ["Bitta CH2 guruhiga","Bitta O atomiga","Bitta N atomiga","Bitta H2O molekulasiga"],
      correctOptionId: 0,
      explanation: "Gomologik qatorda navbatdagi vakilga o'tishda CH2 qo'shiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_6",
      question: "Normal alkan deganda nima tushuniladi?",
      options: ["Halqali tuzilishga ega alkan","Tarmoqlanmagan uglerod zanjirli alkan","Faqat gaz holatidagi alkan","Tarkibida qo'sh bog' bor alkan"],
      correctOptionId: 1,
      explanation: "Normal alkanlarning uglerod skeleti tarmoqlanmagan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_7",
      question: "Izoalkan nimasi bilan normal alkandan farq qiladi?",
      options: ["Kislorod atomiga ega bo'lishi bilan","Uch bog'ga ega bo'lishi bilan","Tarmoqlangan uglerod zanjiri bilan","Faqat qattiq holatda bo'lishi bilan"],
      correctOptionId: 2,
      explanation: "Izoalkanlarda uglerod skeleti tarmoqlangan bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_8",
      question: "Alkan molekulasidagi uglerod atomlari qanday gibridlangan?",
      options: ["sp","sp2","Umuman gibridlanmagan","sp3"],
      correctOptionId: 3,
      explanation: "Slaydda barcha uglerod atomlari sp3-gibridlangan deb berilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_9",
      question: "Alkanlarga xos C–C bog'i qaysi turga kiradi?",
      options: ["Oddiy sigma bog'","Ikki pi bog'","Uch bog'","Ion bog'"],
      correctOptionId: 0,
      explanation: "Alkanlarda faqat oddiy C–C va C–H bog'lar bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_10",
      question: "Alkil radikallarining umumiy formulasi qaysi?",
      options: ["CnH2n+2","CnH2n-2","CnH2n+1","CnHn+2"],
      correctOptionId: 2,
      explanation: "Alkan molekulasidan bitta vodorod ajralsa, CnH2n+1 tarkibli alkil guruhi hosil bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_11",
      question: "CH3 alkil guruhi qanday ataladi?",
      options: ["Etil","Metil","Propil","Butil"],
      correctOptionId: 1,
      explanation: "CH3 guruhining nomi metil.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_12",
      question: "C2H5 alkil guruhi qanday ataladi?",
      options: ["Metil","Propil","Pentil","Etil"],
      correctOptionId: 3,
      explanation: "C2H5 guruhining nomi etil.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_13",
      question: "C3H8 alkanining nomi nima?",
      options: ["Propan","Etan","Butan","Pentan"],
      correctOptionId: 0,
      explanation: "Uchta uglerod atomi saqlagan alkan propan deyiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_14",
      question: "C5H12 alkanining nomi nima?",
      options: ["Geksan","Pentan","Butan","Geptan"],
      correctOptionId: 1,
      explanation: "Besh uglerodli alkan pentan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_15",
      question: "C6H14 qaysi alkanning formulasi?",
      options: ["Pentan","Geptan","Geksan","Oktan"],
      correctOptionId: 2,
      explanation: "Oltita uglerodli alkan geksan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_16",
      question: "Butanning molekulyar formulasi qaysi?",
      options: ["C4H8","C3H8","C5H12","C4H10"],
      correctOptionId: 3,
      explanation: "To'rtta uglerodli alkan C4H10 formulasiga ega.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_17",
      question: "C4H10 uchun uglerod skeletiga ko'ra nechta struktur izomer mavjud?",
      options: ["2 ta","3 ta","4 ta","5 ta"],
      correctOptionId: 0,
      explanation: "Butan va 2-metilpropan C4H10 ning ikki struktur izomeridir.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_18",
      question: "C5H12 uchun uglerod skeletiga ko'ra nechta struktur izomer mavjud?",
      options: ["2 ta","3 ta","4 ta","5 ta"],
      correctOptionId: 1,
      explanation: "Pentanning uchta struktur izomeri bor.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_19",
      question: "CH3–CH2–CH2–CH3 tuzilishli alkan qanday ataladi?",
      options: ["2-metilpropan","Propan","n-butan","n-pentan"],
      correctOptionId: 2,
      explanation: "To'rtta uglerodli tarmoqlanmagan zanjir n-butandir.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_1_20",
      question: "2-metilpropan qaysi alkanning izomeri?",
      options: ["Metan","Etan","Propan","Butan"],
      correctOptionId: 3,
      explanation: "2-metilpropan ham, butan ham C4H10 formulasiga ega.",
      timeLimitSeconds: 20,
    },
  ],
};

export const i3Quiz2: Quiz = {
  id: "I3_2",
  title: "Alkanlar — 2-qism (I3_2)",
  description: "21–40-savollar: Tabiiy manbalar, fizik xossalar va olinish (20s/savol)",
  source: "Abdusalom Saidov slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "i3_2_1",
      question: "Slaydda alkanlarning tabiiy manbalari sifatida qaysi juftlik berilgan?",
      options: ["Dengiz suvi va ohaktosh","Neft va tabiiy gaz","Kvars va osh tuzi","Temir rudasi va qum"],
      correctOptionId: 1,
      explanation: "Alkanlar neft va tabiiy gaz tarkibida uchraydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_2",
      question: "Tabiiy gazning asosiy uglevodorodi qaysi?",
      options: ["Butan","Pentan","Metan","Geksan"],
      correctOptionId: 2,
      explanation: "Slaydda tabiiy gazning asosiy komponenti metan ekani ko'rsatilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_3",
      question: "Ko'mir shaxtalaridan ajraladigan gazning asosiy tarkibiy qismi nima?",
      options: ["Etilen","Azot","Propin","Metan"],
      correctOptionId: 3,
      explanation: "Shaxta gazi tarkibida metan mavjud.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_4",
      question: "Botqoqlik gazi asosan qaysi uglevodoroddan iborat?",
      options: ["Metan","Buten","Benzol","Asetilen"],
      correctOptionId: 0,
      explanation: "Kislorodsiz chirish jarayonida metan hosil bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_5",
      question: "Neftni fraksion haydashdan nima olinadi?",
      options: ["Faqat bitta sof modda","Turli qaynash oralig'idagi neft mahsulotlari","Faqat kislorod va azot","Faqat osh tuzi"],
      correctOptionId: 1,
      explanation: "Benzin, kerosin va dizel yoqilg'isi turli fraksiyalarga misol.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_6",
      question: "Qaysi mahsulot neftni fraksion haydashda ajratiladi?",
      options: ["Oqartirilgan ohak","Mis sulfat","Kerosin","Ammiak"],
      correctOptionId: 2,
      explanation: "Kerosin slaydda neft mahsuloti sifatida berilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_7",
      question: "Slayd bo'yicha C1–C4 alkanlari oddiy sharoitda qanday holatda?",
      options: ["Suyuqlik","Qattiq kristall","Gel","Gaz"],
      correctOptionId: 3,
      explanation: "Metan, etan, propan va butan gaz holatda bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_8",
      question: "Slayd bo'yicha C5–C16 alkanlari oddiy sharoitda qanday holatda?",
      options: ["Suyuqlik","Gaz","Plazma","Qattiq kristall"],
      correctOptionId: 0,
      explanation: "Slaydda C5–C16 vakillari suyuq deb ko'rsatilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_9",
      question: "Slayd bo'yicha C17 dan boshlab alkanlar oddiy sharoitda qanday holatda?",
      options: ["Gaz","Qattiq modda","Plazma","Faqat suvli eritma"],
      correctOptionId: 1,
      explanation: "Uzun zanjirli alkanlar qattiq bo'lishi mumkin.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_10",
      question: "Alkanlar suvda qanday eriydi?",
      options: ["Cheksiz yaxshi","Faqat qizdirilganda to'liq","Juda yomon","Kimyoviy parchalanib eriydi"],
      correctOptionId: 2,
      explanation: "Alkanlar qutbsiz bo'lgani uchun qutbli suvda yomon eriydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_11",
      question: "Alkanlar qaysi erituvchilarda yaxshi eriydi?",
      options: ["Faqat suvda","Faqat suyultirilgan kislotada","Faqat ammiak eritmasida","Qutbsiz organik erituvchilarda"],
      correctOptionId: 3,
      explanation: "Slaydda benzol, efir va xloroform misol sifatida keltirilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_12",
      question: "Suyuq alkanlarning suvga nisbatan zichligi qanday?",
      options: ["Odatda suvdan yengil","Har doim suvdan og'ir","Suv bilan aynan teng","Faqat bosimga bog'liq holda nol"],
      correctOptionId: 0,
      explanation: "Slaydda alkanlar suvdan yengil ekani qayd etilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_13",
      question: "Bir xil formulali normal va tarmoqlangan alkanlardan qaysisining qaynash harorati odatda yuqoriroq?",
      options: ["Har doim tarmoqlanganniki","Normal zanjirliniki","Har ikkisining mutlaqo bir xil","Faqat halqali izomerniki"],
      correctOptionId: 1,
      explanation: "Tarmoqlanmagan izomerda molekulalararo tortishish kuchliroq bo'lishi mumkin.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_14",
      question: "Slaydda n-pentanning qaynash harorati taxminan qancha deb berilgan?",
      options: ["0°C","28°C","36°C","100°C"],
      correctOptionId: 2,
      explanation: "Slaydda n-pentan 36°C, izopentan 28°C deb ko'rsatilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_15",
      question: "Galogenalkanlarni o'zaro biriktirib alkan olishda qaysi metall ishlatiladi?",
      options: ["Temir","Kalsiy","Mis","Natriy"],
      correctOptionId: 3,
      explanation: "R–X + 2Na + X–R → R–R + 2NaX ko'rinishidagi reaksiyada natriy ishlatiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_16",
      question: "Natriy asetatni NaOH bilan qizdirib dekarboksillaganda qaysi alkan hosil bo'ladi?",
      options: ["Metan","Etan","Propan","Butan"],
      correctOptionId: 0,
      explanation: "CH3COONa + NaOH → CH4 + Na2CO3.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_17",
      question: "Natriy asetat elektrolizida qaysi alkan hosil bo'ladi?",
      options: ["Metan","Etan","Propan","Butan"],
      correctOptionId: 1,
      explanation: "Ikki metil radikali birikib C2H6 hosil qiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_18",
      question: "CH3MgI organomagniy birikmasi suv bilan reaksiyaga kirishsa qaysi alkan olinadi?",
      options: ["Etan","Propan","Metan","Butan"],
      correctOptionId: 2,
      explanation: "CH3MgI gidrolizida CH4 hosil bo'lishi slaydda ko'rsatilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_19",
      question: "Alkenni katalizator ishtirokida vodorodlash natijasida nima olinadi?",
      options: ["Aromatik kislota","Spirt","Aldegid","Alkan"],
      correctOptionId: 3,
      explanation: "Qo'sh bog'ga H2 birikib to'yingan uglevodorod hosil bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_2_20",
      question: "Al4C3 karbidini suv bilan gidrolizlaganda qaysi gaz hosil bo'ladi?",
      options: ["Metan","Etilen","Asetilen","Vodorod xlorid"],
      correctOptionId: 0,
      explanation: "Slayddagi tenglamada Al4C3 + 12H2O → 4Al(OH)3 + 3CH4.",
      timeLimitSeconds: 20,
    },
  ],
};

export const i3Quiz3: Quiz = {
  id: "I3_3",
  title: "Alkanlar — 3-qism (I3_3)",
  description: "41–60-savollar: Kimyoviy xossalar va termik o'zgarishlar (20s/savol)",
  source: "Abdusalom Saidov slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "i3_3_1",
      question: "Alkan to'liq yonganda asosan qaysi moddalar hosil bo'ladi?",
      options: ["CO va H2","CO2 va H2O","C va NH3","HCl va NaOH"],
      correctOptionId: 1,
      explanation: "Kislorod yetarli bo'lganda uglerod CO2 ga, vodorod H2O ga aylanadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_2",
      question: "Alkanlarning galogenlanishi odatda qaysi reaksiyalar turiga kiradi?",
      options: ["Polimerlanish","Gidroliz","Almashinish (o'rin olish)","Esterlanish"],
      correctOptionId: 2,
      explanation: "Galogen alkan molekulasidagi vodorod o'rnini egallaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_3",
      question: "Oddiy sharoitda alkanlarga qaysi kuchli oksidlovchi odatda ta'sir etmaydi?",
      options: ["O2 alangada","Havo yuqori haroratda","O2 katalizator ishtirokida","KMnO4"],
      correctOptionId: 3,
      explanation: "Slaydda oddiy sharoitda KMnO4 alkanlarga ta'sir etmasligi aytilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_4",
      question: "Metanni xlorlashda yorug'lik ta'sirida Cl2 dan dastlab nima hosil bo'ladi?",
      options: ["Ikki xlor radikali","Ikki metan molekulasi","Karbonat angidrid","Natriy xlorid"],
      correctOptionId: 0,
      explanation: "Cl2 ning gomolitik uzilishi zanjirli reaksiyani boshlaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_5",
      question: "Metanni xlorlash zanjiri davomida Cl radikali CH4 dan nimani ajratib oladi?",
      options: ["Uglerod atomini","Vodorod atomini","Kislorod atomini","Xlor atomini"],
      correctOptionId: 1,
      explanation: "Cl· + CH4 → HCl + CH3·.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_6",
      question: "CH3 radikali Cl2 bilan reaksiyaga kirishganda asosiy qaysi organik mahsulot hosil bo'ladi?",
      options: ["C2H4","CH3OH","CH3Cl","CCl4"],
      correctOptionId: 2,
      explanation: "CH3· + Cl2 → CH3Cl + Cl·.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_7",
      question: "Ikki CH3 radikali birikishi zanjir reaksiyasining qaysi bosqichiga misol?",
      options: ["Initsirlash","Gidroliz","Kondensatsiya","Zanjirning uzilishi"],
      correctOptionId: 3,
      explanation: "2CH3· → C2H6 bosqichida radikallar yo'qoladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_8",
      question: "Slaydda galogenlarning alkanlar bilan reaksion faollik tartibi qanday berilgan?",
      options: ["F > Cl > Br > I","I > Br > Cl > F","Br > F > I > Cl","Cl > I > F > Br"],
      correctOptionId: 0,
      explanation: "Slaydda yod J belgisi bilan yozilgan; bu yerda I xalqaro belgi ishlatilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_9",
      question: "Slaydga ko'ra qaysi galogenlash ko'proq regioselektiv?",
      options: ["Ftorlash","Bromlash","Xlorlash","Barchasi teng"],
      correctOptionId: 1,
      explanation: "Bromlash xlorlashga nisbatan ma'lum o'rindagi C–H bog'iga tanlovchanroq.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_10",
      question: "Alkanni nitrolash natijasida qaysi turdagi organik modda hosil bo'ladi?",
      options: ["Spirt","Alken","Nitroalkan","Efir"],
      correctOptionId: 2,
      explanation: "Nitrolanishda vodorod o'rniga NO2 guruhi kiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_11",
      question: "Alkanlarning sulfoxlorlanishida hosil bo'ladigan mahsulot qaysi turga kiradi?",
      options: ["Alken","Keton","Spirt","Alkilsulfonilxlorid"],
      correctOptionId: 3,
      explanation: "Mahsulotning umumiy ko'rinishi R–SO2Cl.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_12",
      question: "Alkanlarning sulfooksidlanishida qaysi birikmalar hosil bo'lishi mumkin?",
      options: ["Alkansulfon kislotalar","Faqat alkenlar","Faqat aminlar","Faqat alkilgalogenidlar"],
      correctOptionId: 0,
      explanation: "Slaydda R–SO3H turidagi mahsulotlar berilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_13",
      question: "Freonlar kimyoviy jihatdan qanday birikmalar?",
      options: ["Alkanlarning faqat kislorodli hosilalari","Quyi alkanlarning ftorxlorli hosilalari","Faqat alkinlarning bromli hosilalari","Faqat aromatik uglevodorodlar"],
      correctOptionId: 1,
      explanation: "Slaydda freonlar quyi alkanlarning ftorxlorli hosilalari deb ta'riflangan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_14",
      question: "Piroliz atamasi nimani anglatadi?",
      options: ["Sovitib kristallantirishni","Filtrlashni","Qizdirilganda moddaning parchalanishini","Suvda eritishni"],
      correctOptionId: 2,
      explanation: "Alkanlar yuqori haroratda parchalanishi mumkin.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_15",
      question: "Alkanning degidrogenlanishida nima ajralib chiqadi?",
      options: ["H2O","CO2","HCl","H2"],
      correctOptionId: 3,
      explanation: "CnH2n+2 → CnH2n + H2.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_16",
      question: "Alkanning degidrogenlanishi natijasida organik mahsulot sifatida nima hosil bo'lishi mumkin?",
      options: ["Alken","Karbonat kislota","Oqsil","Tuz"],
      correctOptionId: 0,
      explanation: "Vodorod ajralishi natijasida alkan alken tarkibiga o'tadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_17",
      question: "Kreking jarayonining asosiy maqsadi nima?",
      options: ["Kichik molekulalarni faqat polimerlash","Og'ir uglevodorodlarni kichikroq molekulalarga parchalash","Suvni elektroliz qilish","Tuzlarni kristallantirish"],
      correctOptionId: 1,
      explanation: "Neftning og'ir fraksiyalaridan yengil uglevodorodlar olinadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_18",
      question: "Slayddagi oktan krekingi misolida C8H18 qaysi juftlikka parchalanadi?",
      options: ["C2H6 + C6H12O","CH4 + C7H16","C4H10 + C4H8","C8H16 + O2"],
      correctOptionId: 2,
      explanation: "C8H18 → C4H10 + C4H8 tenglama atomlar soni bo'yicha muvozanatlangan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_19",
      question: "Alkanlarning izomerlanishida n-alkan qanday birikmaga aylanishi mumkin?",
      options: ["Spirtga","Aldegidga","Karbonat kislotaga","Izoalkanga"],
      correctOptionId: 3,
      explanation: "Slaydda n-alkan va izoalkan o'rtasida muvozanat hosil bo'lishi ko'rsatilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "i3_3_20",
      question: "Izooktanning sistematik nomi qaysi?",
      options: ["2,2,4-trimetilpentan","n-oktan","2-metilpropan","3-etilgeksan"],
      correctOptionId: 0,
      explanation: "Slaydda izooktan C8H18 ning 2,2,4-trimetilpentan tuzilishi berilgan.",
      timeLimitSeconds: 20,
    },
  ],
};

export const allI3Quizzes: Quiz[] = [i3Quiz1, i3Quiz2, i3Quiz3];
