import { Quiz } from "./types.js";

/**
 * Kolloid kimyo (KK_M1) — Telegram Quiz savollari to'plami
 * 60 ta savol 3 ta mustaqil quizga bo'lingan: KK1_1, KK1_2, KK1_3
 * Har bir savolga 20 soniya beriladi. Faqat guruhlarda o'tkaziladi.
 * Har safar savollar va 4 ta javob varianti alohida aralashtiriladi.
 */

export const kk1Quiz1: Quiz = {
  id: "KK1_1",
  title: "Kolloid kimyo — 1-qism (KK1_1)",
  description: "01–20-savollar: Kolloid kimyo asoslari, dispers sistemalar va sirt hodisalari (20s/savol)",
  source: "Bahora Nayimova slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "kk1_1_1",
      question: "Kolloid kimyo asosan nimani o‘rganadi?",
      options: ["Yuqori dispers sistemalar va sirt hodisalarini","Faqat atom yadrosidagi reaksiyalarni","Faqat gazlarning ideal qonunlarini","Faqat kristall panjaralarini"],
      correctOptionId: 0,
      explanation: "Fan yuqori dispers sistemalar va fazalararo sirt bilan bog‘liq hodisalarni o‘rganadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_2",
      question: "Quyidagilardan qaysi biri dispers sistema tarkibidagi ikki asosiy qism?",
      options: ["Kation va anion","Dispers faza va dispersion muhit","Erituvchi va katalizator","Metall va nometall"],
      correctOptionId: 1,
      explanation: "Dispers sistema tarqalgan modda va uni o‘rab turgan uzluksiz muhitdan iborat.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_3",
      question: "Dispers faza deb nimaga aytiladi?",
      options: ["Faqat idish devoriga","Faqat eritmadagi ionlarga","Muhitda mayda zarrachalar holida tarqalgan moddaga","Faqat gaz holatdagi moddaga"],
      correctOptionId: 2,
      explanation: "Dispers faza dispersion muhit ichida taqsimlangan modda hisoblanadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_4",
      question: "Dispersion muhit qanday qism?",
      options: ["Faqat cho‘kmadan iborat qism","Faqat qattiq zarracha","Zarrachalar sirtidagi ion","Dispers fazani o‘rab turgan uzluksiz faza"],
      correctOptionId: 3,
      explanation: "Dispers faza aynan dispersion muhit ichida tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_5",
      question: "Sutdagi yog‘ tomchilari nimaga misol bo‘ladi?",
      options: ["Dispers fazaga","Yarim o‘tkazuvchi membranaga","Cho‘kmaga","Gaz muhitiga"],
      correctOptionId: 0,
      explanation: "Sutdagi yog‘ tomchilari suyuq muhitda tarqalgan fazadir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_6",
      question: "Tuman tarkibidagi suv tomchilari uchun dispersion muhit nima?",
      options: ["Suv","Havo","Tuproq","Yog‘"],
      correctOptionId: 1,
      explanation: "Suv tomchilari havoda tarqalgan suyuq aerozolni hosil qiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_7",
      question: "Disperslik darajasi D zarracha o‘lchami a orqali qanday ifodalanadi?",
      options: ["D = a²","D = a + 1","D = 1/a","D = a/2"],
      correctOptionId: 2,
      explanation: "Zarracha o‘lchami kamaygan sari disperslik ortadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_8",
      question: "Zarracha o‘lchami kichrayganda, disperslik darajasi qanday o‘zgaradi?",
      options: ["Nolga tenglashadi","O‘zgarmaydi","Kamayadi","Ortadi"],
      correctOptionId: 3,
      explanation: "D = 1/a munosabatiga ko‘ra a kamayishi D ni oshiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_9",
      question: "Kolloid zarrachalarning slaydda berilgan o‘lcham oralig‘i qaysi?",
      options: ["1–100 nm","0,001–0,1 nm","1–100 mm","100–1000 mkm"],
      correctOptionId: 0,
      explanation: "Taqdimotda kolloid dispers faza uchun 1–100 nm oralig‘i berilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_10",
      question: "Slayddagi tasnifga ko‘ra chin eritmadagi zarrachalar o‘lchami qanday?",
      options: ["100 nm dan katta","1 nm dan kichik","1–100 mkm","1–100 mm"],
      correctOptionId: 1,
      explanation: "Chin eritmada modda molekula yoki ion darajasida tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_11",
      question: "Slayddagi tasnifga ko‘ra dag‘al dispers sistemada zarracha o‘lchami qancha?",
      options: ["1 nm dan kichik","Aynan 1 nm","100 nm dan katta","1–10 nm"],
      correctOptionId: 2,
      explanation: "Dag‘al dispers sistemaning zarrachalari kolloid zarrachalardan yirikroq.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_12",
      question: "Qaysi sistemada Tindal effekti odatda kuzatilmaydi?",
      options: ["Kraxmal zolida","Kolloid oltin zolida","Sutda","Chin eritmada"],
      correctOptionId: 3,
      explanation: "Chin eritma zarrachalari yorug‘likni sezilarli sochmaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_13",
      question: "Tindal effekti nimani anglatadi?",
      options: ["Kolloid eritmada yorug‘lik nurining yo‘li ko‘rinishini","Qattiq moddaning erib ketishini","Eritmaning qaynashini","Gazning siqilishini"],
      correctOptionId: 0,
      explanation: "Kolloid zarrachalar nurni sochgani uchun nur yo‘li ko‘rinadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_14",
      question: "Kolloid eritma tashqi ko‘rinishidan bir jinsli tuyulsa ham, aslida qanday sistema?",
      options: ["Elementar","Geterogen","Faqat gazsimon","Mutlaqo zarrachasiz"],
      correctOptionId: 1,
      explanation: "Unda dispers faza va dispersion muhit mavjud.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_15",
      question: "Qaysi usul kolloid eritmadagi kichik molekulalarni membrana orqali ajratishga xizmat qiladi?",
      options: ["Bug‘latish","Kristallash","Dializ","Eritish"],
      correctOptionId: 2,
      explanation: "Kolloid zarrachalar yarim o‘tkazuvchi membranadan odatda o‘tmaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_16",
      question: "Loyqa suvdagi yirik zarrachalar vaqt o‘tishi bilan nega cho‘kadi?",
      options: ["Yorug‘lik ta’sirida parchalangani uchun","Har doim bug‘langani uchun","Barchasi membranadan o‘tgani uchun","Og‘irlik kuchi ta’sirida sedimentatsiyalangani uchun"],
      correctOptionId: 3,
      explanation: "Dag‘al dispers zarrachalar cho‘kma hosil qilishi mumkin.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_17",
      question: "Dag‘al dispers sistemadagi qattiq zarrachalarni ko‘pincha qaysi usul bilan ajratish mumkin?",
      options: ["Oddiy filtrlash","Faqat dializ","Faqat optik o‘lchash","Faqat adsorbsiya"],
      correctOptionId: 0,
      explanation: "Yirik dispers faza zarrachalari filtrda ushlanadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_18",
      question: "Solishtirma sirtning massa bo‘yicha ifodasi qaysi?",
      options: ["S = m/A","S = A/m","S = A × m","S = A + m"],
      correctOptionId: 1,
      explanation: "A — umumiy sirt maydoni, m — modda massasi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_19",
      question: "Bir xil hajmdagi kub 27 ta teng kichik kubga ajratilsa, umumiy sirt maydoni qanday o‘zgaradi?",
      options: ["27 marta kamayadi","O‘zgarmaydi","3 marta ortadi","3 marta kamayadi"],
      correctOptionId: 2,
      explanation: "Slayddagi misolda 6a² yuzadan 18a² yuzaga o‘tiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_1_20",
      question: "Zarralarni maydalash natijasida nima ortadi?",
      options: ["Faqat moddaning massasi","Faqat moddaning hajmi","Faqat atomlar soni","Umumiy sirt maydoni"],
      correctOptionId: 3,
      explanation: "Maydalash bir xil massadagi moddaning ochiq sirtini kattalashtiradi.",
      timeLimitSeconds: 20,
    },
  ],
};

export const kk1Quiz2: Quiz = {
  id: "KK1_2",
  title: "Kolloid kimyo — 2-qism (KK1_2)",
  description: "21–40-savollar: Sirt energiyasi, adsorbsiya va dispers sistemalar xossalari (20s/savol)",
  source: "Bahora Nayimova slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "kk1_2_1",
      question: "Sirt qatlamidagi molekulalar nega ortiqcha energiyaga ega?",
      options: ["Ularga ta’sir etuvchi kuchlar muvozanatlashmagani uchun","Ularning massasi doimo ortgani uchun","Ular kimyoviy elementga aylangani uchun","Ular harakatsiz bo‘lgani uchun"],
      correctOptionId: 0,
      explanation: "Ichki qatlamdan farqli ravishda sirt molekulalariga kuchlar bir xil ta’sir etmaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_2",
      question: "Slaydda sirt energiyasi qanday ifodalangan?",
      options: ["Gs = S/σ","Gs = σS","Gs = m/σ","Gs = σ + m"],
      correctOptionId: 1,
      explanation: "σ — sirt tarangligi, S — sirt maydoni.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_3",
      question: "Nima sababdan erkin suyuqlik tomchisi shar shakliga yaqinlashadi?",
      options: ["Uning zichligi nol bo‘lgani uchun","Uning massasi ortgani uchun","Sirt maydonini kamaytirishga intilgani uchun","Doimo muzlagani uchun"],
      correctOptionId: 2,
      explanation: "Sirt tarangligi sirt energiyasini kamaytirishga xizmat qiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_4",
      question: "Adsorbsiya nima?",
      options: ["Moddaning faqat bug‘lanishi","Molekulalarning faqat cho‘kishi","Qattiq moddaning erishi","Moddaning boshqa modda sirtida to‘planishi"],
      correctOptionId: 3,
      explanation: "Adsorbsiya fazalararo sirtda sodir bo‘ladigan to‘planish jarayonidir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_5",
      question: "Adsorbsiyada yutuvchi sirt nima deb ataladi?",
      options: ["Adsorbent","Adsorbat","Dispers faza","Emulgator"],
      correctOptionId: 0,
      explanation: "Adsorbent — yutuvchi modda yoki sirt.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_6",
      question: "Adsorbsiyada yutilayotgan modda nima deb ataladi?",
      options: ["Koagulyant","Adsorbat","Gel","Elektrod"],
      correctOptionId: 1,
      explanation: "Adsorbat adsorbent sirtida to‘planadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_7",
      question: "Quyidagilardan qaysi biri samarali adsorbent sifatida keltirilgan?",
      options: ["Toza shisha","Distillangan suv","Aktivlangan ko‘mir","Osh tuzining chin eritmasi"],
      correctOptionId: 2,
      explanation: "Aktivlangan ko‘mir katta solishtirma sirtga ega.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_8",
      question: "Adsorbsiya muvozanati qachon qaror topadi?",
      options: ["Harorat mutlaqo nolga tushganda","Dispers faza bug‘langanda","Adsorbent erib ketganda","Adsorbsiya va desorbsiya tezliklari tenglashganda"],
      correctOptionId: 3,
      explanation: "Muvozanatda sirtga kelish va sirtdan ketish tezliklari teng bo‘ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_9",
      question: "Namlanish yoki ho‘llanish nimani bildiradi?",
      options: ["Suyuqlikning qattiq sirt bo‘ylab tarqalish qobiliyatini","Zarrachalarning gravitatsion cho‘kishini","Gazning suyuqlikdan chiqishini","Tuzning kristallanishini"],
      correctOptionId: 0,
      explanation: "Ho‘llanish suyuqlik va qattiq sirt orasidagi hodisadir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_10",
      question: "Kapillyarlik nima?",
      options: ["Qattiq moddaning yonishi","Ingichka naychada suyuqlik sathining ko‘tarilishi yoki pasayishi","Eritmada kristallarning paydo bo‘lishi","Zarralarning elektr maydonida harakati"],
      correctOptionId: 1,
      explanation: "Kapillyarlik sirt hodisalaridan biridir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_11",
      question: "Qattiq zarrachalar gaz muhitida tarqalsa, sistema qanday ataladi?",
      options: ["Emulsiya","Suyuq ko‘pik","Qattiq aerozol","Qattiq zol"],
      correctOptionId: 2,
      explanation: "Tutun va chang qattiq aerozolga misol bo‘ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_12",
      question: "Suyuq tomchilar gaz muhitida tarqalsa, qanday sistema hosil bo‘ladi?",
      options: ["Suspenziya","Gel","Qattiq ko‘pik","Suyuq aerozol"],
      correctOptionId: 3,
      explanation: "Tuman va purkagich tomchilari suyuq aerozoldir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_13",
      question: "Havodagi chang qanday dispers sistemaga misol?",
      options: ["Qattiq aerozolga","Emulsiyaga","Suyuq ko‘pikka","Chin eritmaga"],
      correctOptionId: 0,
      explanation: "Changning qattiq zarrachalari gaz muhitida tarqalgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_14",
      question: "Sovun ko‘pigida qaysi faza qaysi muhitda tarqalgan?",
      options: ["Suyuqlik qattiq muhitda","Gaz suyuqlik muhitida","Qattiq modda gaz muhitida","Qattiq modda suyuqlik muhitida"],
      correctOptionId: 1,
      explanation: "Suyuq ko‘pikda gaz pufakchalari suyuqlik ichida bo‘ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_15",
      question: "Emulsiya qanday dispers sistema?",
      options: ["Gazning gazdagi eritmasi","Qattiq moddaning qattiqdagi aralashmasi","Bir-birida erimaydigan ikki suyuqlikdan iborat sistema","Ionlarning suvdagi chin eritmasi"],
      correctOptionId: 2,
      explanation: "Bir suyuqlik ikkinchisida mayda tomchilar holida tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_16",
      question: "“Moy suvda” emulsiyasida dispers faza qaysi?",
      options: ["Havo","Suv","Emulgatorning qattiq qatlami","Moy tomchilari"],
      correctOptionId: 3,
      explanation: "Moy tomchilari suvli dispersion muhitda tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_17",
      question: "“Suv moyda” emulsiyasida dispersion muhit qaysi?",
      options: ["Moy","Suv","Havo","Tuz"],
      correctOptionId: 0,
      explanation: "Suv tomchilari moyli muhit ichida tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_18",
      question: "Emulgatorning asosiy vazifasi nima?",
      options: ["Zarrachalarni qizdirish","Sirt tarangligini kamaytirib, tomchilarning birikishini sekinlashtirish","Suyuqlikni butunlay bug‘latish","Barcha tomchilarni darhol cho‘ktirish"],
      correctOptionId: 1,
      explanation: "Emulgator fazalararo sirtda emulsiyani barqarorlashtiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_19",
      question: "Emulsiya buzilib, mayda tomchilar yiriklashsa, bu jarayon nima deyiladi?",
      options: ["Dializ","Diffuziya","Koalessensiya","Elektroosmos"],
      correctOptionId: 2,
      explanation: "Tomchilar birikib, yirik tomchilar va ajralgan fazalarni hosil qiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_2_20",
      question: "Suyuq ko‘pikda gaz pufakchalari nimaning yordamida bir-biridan ajralgan?",
      options: ["Qattiq kristallar bilan","Elektr simlar bilan","Vakuum bilan","Yupqa suyuqlik pardalari bilan"],
      correctOptionId: 3,
      explanation: "Pufakchalar orasida suyuq pardalar mavjud.",
      timeLimitSeconds: 20,
    },
  ],
};

export const kk1Quiz3: Quiz = {
  id: "KK1_3",
  title: "Kolloid kimyo — 3-qism (KK1_3)",
  description: "41–60-savollar: Zol va gellar, optik va kinetik xossalar, koagulyatsiya (20s/savol)",
  source: "Bahora Nayimova slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "kk1_3_1",
      question: "Zol va gelning asosiy farqi qaysi?",
      options: ["Zol oqimchan, gel esa fazoviy to‘r hosil qilgan","Zol doimo gaz, gel doimo metall","Zolda hech qanday zarracha bo‘lmaydi","Gel faqat chin eritmadan iborat"],
      correctOptionId: 0,
      explanation: "Gelda dispers faza strukturasi sabab oqimchanlik past bo‘ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_2",
      question: "Zolning gelga aylanishi nima deyiladi?",
      options: ["Adsorbsiya","Gelatsiya","Sedimentatsiya","Dializ"],
      correctOptionId: 1,
      explanation: "Slaydda zol–gel o‘tishi gelatsiya deb atalgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_3",
      question: "Suspenziyada qaysi faza qaysi muhitda tarqaladi?",
      options: ["Gaz qattiq muhitda","Suyuqlik gaz muhitida","Qattiq zarrachalar suyuqlik muhitida","Gaz gaz muhitida"],
      correctOptionId: 2,
      explanation: "Suspenziya dag‘al dispers sistemadir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_4",
      question: "Suspenziya zarrachalarining cho‘kishi nima deyiladi?",
      options: ["Ho‘llanish","Adsorbsiya","Peptizatsiya","Sedimentatsiya"],
      correctOptionId: 3,
      explanation: "Og‘irlik kuchi ta’sirida zarralar pastga siljiydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_5",
      question: "Suspenziya turg‘unligini oshirish uchun slaydda qaysi usul keltirilgan?",
      options: ["Zarrachalar o‘lchamini kamaytirish","Zarrachalarni yanada yiriklashtirish","Muhitni to‘liq bug‘latish","Idishni ochiq qoldirish"],
      correctOptionId: 0,
      explanation: "Mayda zarrachalar sekinroq cho‘kadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_6",
      question: "Braun harakatining bevosita sababi nima?",
      options: ["Faqat yorug‘lik nuri","Dispersion muhit molekulalarining zarrachaga zarbalari","Faqat elektr toki","Idishning rangi"],
      correctOptionId: 1,
      explanation: "Notekis molekulyar zarbalar tartibsiz harakatni keltirib chiqaradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_7",
      question: "Braun harakati qaysi holatda kuchayadi?",
      options: ["Harorat pasayib, zarracha yiriklashganda","Zarracha harakatsiz qotganda","Harorat oshib, zarracha kichrayganda","Faqat eritma rangsizlanganda"],
      correctOptionId: 2,
      explanation: "Slaydda kichikroq zarracha va yuqoriroq harorat harakatni kuchaytirishi aytilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_8",
      question: "Diffuziya qaysi yo‘nalishda sodir bo‘ladi?",
      options: ["Past konsentratsiyadan yuqoriga","Faqat pastdan yuqoriga","Faqat qattiq sirtda","Yuqori konsentratsiyadan past konsentratsiyaga"],
      correctOptionId: 3,
      explanation: "Modda o‘z-o‘zidan konsentratsiya farqi bo‘yicha tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_9",
      question: "Elektroforez nima?",
      options: ["Zaryadlangan zarrachalarning elektr maydonida harakatlanishi","Gazning suyuqlikka yutilishi","Emulsiya tomchilarining birikishi","Membrana orqali suvning o‘tishi"],
      correctOptionId: 0,
      explanation: "Elektr maydoni zaryadlangan kolloid zarrachalarni siljitadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_10",
      question: "Elektroosmos nima?",
      options: ["Zarrachaning filtrda ushlanishi","Suyuqlikning g‘ovak muhit yoki kapillyarda elektr maydoni ta’sirida siljishi","Suyuqlikning qaynashi","Yorug‘likning kolloid eritmada sochilishi"],
      correctOptionId: 1,
      explanation: "Elektroosmosda siljiydigan qism suyuqlikdir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_11",
      question: "Zeta-potensial qiymati katta bo‘lganda zarrachalar odatda qanday ta’sirlashadi?",
      options: ["Bir zumda bug‘lanadi","Barchasi elektrsizlanadi","Bir-birini kuchliroq itaradi","Darhol kristallanadi"],
      correctOptionId: 2,
      explanation: "Elektr itarilish kuchi agregatsiyani qiyinlashtiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_12",
      question: "Sedimentatsion barqarorlik nimani bildiradi?",
      options: ["Zarralarning tez birikishini","Faqat sirtning ho‘llanishini","Yorug‘lik yutilishini","Zarrachalarning cho‘kmasdan muhitda saqlanishini"],
      correctOptionId: 3,
      explanation: "Bu barqarorlik cho‘kishga qarshi turish qobiliyatidir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_13",
      question: "Agregativ barqarorlik nimani bildiradi?",
      options: ["Zarrachalarning birikib yirik agregat hosil qilmasligini","Zarralarning faqat rangini saqlashini","Suyuqlikning muzlamasligini","Faqat gazning siqilishini"],
      correctOptionId: 0,
      explanation: "Agregativ barqaror sistema zarrachalari bir-biriga yopishib ketmaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_14",
      question: "Koagulyatsiya natijasida qanday o‘zgarish yuz beradi?",
      options: ["Har bir zarracha molekulaga parchalanadi","Kolloid zarrachalar birikib yirik agregatlar hosil qiladi","Barcha zarralar membranadan o‘tadi","Sirt maydoni cheksiz ortadi"],
      correctOptionId: 1,
      explanation: "Agregatlar hosil bo‘lishi kolloid sistema barqarorligini buzadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_15",
      question: "Elektrolit qo‘shilishi koagulyatsiyani nega tezlashtirishi mumkin?",
      options: ["Zarralarni doimo qizdirgani uchun","Suvni butunlay yo‘qotgani uchun","Qo‘sh elektr qavatni siqib, itarilish kuchini kamaytirgani uchun","Tindal effektini kuchaytirgani uchun"],
      correctOptionId: 2,
      explanation: "Zarrachalar orasidagi elektr itarilish kamayganda ular yaqinlashadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_16",
      question: "Peptizatsiya qanday jarayon?",
      options: ["Gazning ko‘pikka aylanishi","Zarrachalarning gravitatsion cho‘kishi","Eritmaning qaynashi","Koagulyatsiyaga teskari, agregatlarning qayta maydalanishi"],
      correctOptionId: 3,
      explanation: "Peptizatsiya birikkan zarrachalarni qayta disperslaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_17",
      question: "Oqava suvni tozalashda qaysi kolloid kimyo jarayonlari qo‘llanadi?",
      options: ["Koagulyatsiya, flokulyatsiya va adsorbsiya","Faqat sublimatsiya","Faqat kristallanish","Faqat yonish"],
      correctOptionId: 0,
      explanation: "Slaydda shu usullar oqava suvni tozalash uchun berilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_18",
      question: "Kolloid tizimning barqarorligiga qaysi tashqi omillar ta’sir qilishi mumkin?",
      options: ["Faqat idishning shakli","pH, ion kuchi, harorat va elektrolit konsentratsiyasi","Faqat yorliqning rangi","Faqat laboratoriya manzili"],
      correctOptionId: 1,
      explanation: "Muhit sharoiti zarrachalararo ta’sirni o‘zgartiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_19",
      question: "Kolloid zarrachalarning optik xossalari asosan nimaga bog‘liq?",
      options: ["Faqat idish hajmiga","Faqat eritma yorlig‘iga","Yorug‘likni sochishi va yutishiga","Faqat cho‘kish tezligiga"],
      correctOptionId: 2,
      explanation: "Tindal effekti aynan yorug‘lik sochilishi bilan bog‘liq.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk1_3_20",
      question: "Suvdagi rangli ifloslantiruvchini adsorbsiyalab ajratishda qaysi modda mos?",
      options: ["Faqat toza suv","Faqat osh tuzi","Faqat havo","Aktivlangan ko‘mir"],
      correctOptionId: 3,
      explanation: "Aktivlangan ko‘mir sirtida erigan moddalar to‘planishi mumkin.",
      timeLimitSeconds: 20,
    },
  ],
};

