import { Quiz } from "./types.js";

/**
 * Kolloid kimyo (KK_M2) — Dispers sistemalarning tasnifi va olinishi
 * 60 ta savol 3 ta mustaqil quizga bo'lingan: KK2_1, KK2_2, KK2_3
 * Har bir savolga 20 soniya beriladi. Faqat guruhlarda o'tkaziladi.
 * Har safar savollar va 4 ta javob varianti alohida aralashtiriladi.
 */

export const kk2Quiz1: Quiz = {
  id: "KK2_1",
  title: "Kolloid kimyo — 2-mavzu 1-qism (KK2_1)",
  description: "01–20-savollar: Dispers sistema va asosiy turlari (20s/savol)",
  source: "Bahora Nayimova slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "kk2_1_1",
      question: "Dispers sistema qanday sistema?",
      options: ["Faqat bitta sof moddadan iborat sistema","Bir moddaning mayda zarrachalari boshqa modda hajmida tarqalgan geterogen sistema","Faqat ikki gazning molekulyar aralashmasi","Faqat kristall moddalardan iborat sistema"],
      correctOptionId: 1,
      explanation: "Dispers faza zarrachalari dispersion muhit hajmida tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_2",
      question: "Suvda tarqalgan loy zarrachalari sistemaning qaysi qismini tashkil qiladi?",
      options: ["Dispers fazani","Dispersion muhitni","Erituvchining bug'ini","Yarim o'tkazuvchan pardani"],
      correctOptionId: 0,
      explanation: "Loyning mayda zarrachalari tarqalgan faza, suv esa uzluksiz muhitdir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_3",
      question: "Dispers fazani o'rab turuvchi uzluksiz qism nima deyiladi?",
      options: ["Adsorbent","Cho'kma","Dispersion muhit","Elektrolit"],
      correctOptionId: 2,
      explanation: "Dispersion muhit tarqalgan zarrachalarni o'rab turadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_4",
      question: "Zarrachalar o'lchami kamayganda disperslik darajasi qanday o'zgaradi?",
      options: ["O'zgarmaydi","Nolga tenglashadi","Kamayadi","Ortadi"],
      correctOptionId: 3,
      explanation: "Slaydda disperslik darajasi D = 1/d deb berilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_5",
      question: "Slaydda disperslik darajasi qaysi formula bilan ifodalangan?",
      options: ["D = d²","D = 1/d","D = d + 1","D = d/2"],
      correctOptionId: 1,
      explanation: "d — zarracha o'lchami; u kichrayganda D ortadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_6",
      question: "Slayd tasnifiga ko'ra zarracha o'lchami 1 nm dan kichik bo'lgan sistema qaysi?",
      options: ["Dag'al dispers sistema","Ko'pik","Molekulyar-dispers sistema","Suspenziya"],
      correctOptionId: 2,
      explanation: "Molekulyar-dispers sistemalarda zarrachalar molekula yoki ion holatida tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_7",
      question: "Slayd tasnifiga ko'ra 1–1000 nm o'lcham oralig'i qaysi sistemaga tegishli?",
      options: ["Kolloid-dispers sistemaga","Faqat molekulyar eritmaga","Faqat gaz aralashmasiga","Dag'al dispers sistemaga"],
      correctOptionId: 0,
      explanation: "Slaydda kolloid-dispers sistema uchun shu oraliq ko'rsatilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_8",
      question: "Slaydda dag'al dispers sistema zarrachalari qanday o'lchamda berilgan?",
      options: ["1 nm dan kichik","Aynan 1 nm","1–10 nm","1000 nm dan katta"],
      correctOptionId: 3,
      explanation: "Dag'al dispers sistemalarda zarrachalar nisbatan yirik bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_9",
      question: "Qaysi holat molekulyar-dispers sistemaga xos?",
      options: ["Yorug'likning kuchli sochilishi","Tinch holatda tez cho'kish","Tindal effektining kuzatilmasligi","Zarrachalarning oddiy ko'z bilan ko'rinishi"],
      correctOptionId: 2,
      explanation: "Haqiqiy eritmalarda Tindal effekti kuzatilmaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_10",
      question: "Qaysi holat kolloid-dispers sistemaga xos?",
      options: ["Zarrachaning oddiy ko'z bilan aniq ko'rinishi","Yorug'lik sochilishi tufayli Tindal effektining kuzatilishi","Tinch holatda darhol cho'kish","Faqat gaz muhitida mavjud bo'lish"],
      correctOptionId: 1,
      explanation: "Kolloid zarrachalar yorug'likni sochadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_11",
      question: "Dag'al dispers sistemada tinch holatda ko'pincha qanday jarayon yuz beradi?",
      options: ["Zarrachalar butunlay ionlarga ajraladi","Dispers faza yo'qoladi","Zarralar molekulalarga aylanadi","Zarrachalar cho'kadi"],
      correctOptionId: 3,
      explanation: "Yirik zarrachalar tortishish kuchi ta'sirida cho'kishi mumkin.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_12",
      question: "Zarracha o'lchamiga ko'ra to'g'ri ketma-ketlikni toping (kichikdan kattaga).",
      options: ["Molekulyar-dispers → kolloid-dispers → dag'al dispers","Dag'al dispers → molekulyar-dispers → kolloid-dispers","Kolloid-dispers → dag'al dispers → molekulyar-dispers","Molekulyar-dispers → dag'al dispers → kolloid-dispers"],
      correctOptionId: 0,
      explanation: "Slaydda chegaralar mos ravishda <1 nm, 1–1000 nm va >1000 nm.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_13",
      question: "Aerozolda dispersion muhit qaysi agregat holatda bo'ladi?",
      options: ["Qattiq","Suyuq","Gaz","Plazma"],
      correctOptionId: 2,
      explanation: "Aerozol — suyuq yoki qattiq zarrachalar gazda tarqalgan sistema.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_14",
      question: "Tuman qanday aerozol turiga misol?",
      options: ["Qattiq aerozol","Suyuq aerozol","Gaz-gaz eritmasi","Qattiq zol"],
      correctOptionId: 1,
      explanation: "Tumanda suyuq suv tomchilari havoda tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_15",
      question: "Chang qaysi aerozol turiga misol?",
      options: ["Qattiq aerozol","Suyuq aerozol","Emulsiya","Gel"],
      correctOptionId: 0,
      explanation: "Changda qattiq zarrachalar gaz muhitida tarqalgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_16",
      question: "Suyuq aerozolda dispers faza nimadan iborat?",
      options: ["Gaz pufakchalaridan","Qattiq metall bo'laklaridan","Ionlardan","Mayda suyuqlik tomchilaridan"],
      correctOptionId: 3,
      explanation: "Tuman va purkagich aerozoli bunga misol.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_17",
      question: "Qattiq aerozolda dispers faza nimadan iborat?",
      options: ["Faqat suv tomchilaridan","Mayda qattiq zarrachalardan","Faqat erigan ionlardan","Gaz pufakchalaridan"],
      correctOptionId: 1,
      explanation: "Chang va tutunda qattiq zarrachalar havoda tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_18",
      question: "Zarrachalari 1–1000 nm bo'lgan va dispersion muhiti suyuq sistema nima deyiladi?",
      options: ["Ko'pik","Molekulyar eritma","Zol","Qattiq aerozol"],
      correctOptionId: 2,
      explanation: "Slaydda zollar suyuq muhitdagi kolloid-dispers sistemalar deb ta'riflangan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_19",
      question: "Oltin zoli qaysi sistemaga misol bo'ladi?",
      options: ["Zolga","Ko'pikka","Emulsiyaga","Qattiq aerozolga"],
      correctOptionId: 0,
      explanation: "Oltin zoli slayddagi zol misollaridan biri.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_1_20",
      question: "Loyqa suv qaysi sistemaga misol?",
      options: ["Molekulyar eritma","Gel","Gaz aerozoli","Suspenziya"],
      correctOptionId: 3,
      explanation: "Suyuqlik muhitida yirik qattiq zarrachalar tarqalgan.",
      timeLimitSeconds: 20,
    },
  ],
};

export const kk2Quiz2: Quiz = {
  id: "KK2_2",
  title: "Kolloid kimyo — 2-mavzu 2-qism (KK2_2)",
  description: "21–40-savollar: Fazalar, barqarorlik va tasnif (20s/savol)",
  source: "Bahora Nayimova slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "kk2_2_1",
      question: "Suspenziyada dispers faza va dispersion muhit mos ravishda qanday?",
      options: ["Gaz va suyuqlik","Qattiq modda va suyuqlik","Suyuqlik va gaz","Gaz va qattiq modda"],
      correctOptionId: 1,
      explanation: "Suspenziya suyuq muhitda yirik qattiq zarrachalar tarqalishidan hosil bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_2",
      question: "Suspenziya tinch qo'yilganda nima kuzatilishi mumkin?",
      options: ["Gaz pufakchalari paydo bo'ladi","Molekulalar ionlarga bo'linadi","Yirik qattiq zarrachalar cho'kadi","Suyuqlik gazga aylanadi"],
      correctOptionId: 2,
      explanation: "Slaydda sedimentatsiya suspenziyaga xos hodisa sifatida berilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_3",
      question: "Emulsiyada dispers faza qanday bo'ladi?",
      options: ["Boshqa suyuqlikdagi mayda suyuqlik tomchilari","Gaz muhitidagi qattiq zarrachalar","Qattiq moddadagi ionlar","Faqat gaz pufakchalari"],
      correctOptionId: 0,
      explanation: "O'zaro aralashmaydigan ikki suyuqlikdan biri ikkinchisida tomchi holida tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_4",
      question: "Moy/suv (M/S) emulsiyasida qaysi qism mayda tomchilar holida tarqalgan?",
      options: ["Suv","Havo","Qattiq kukun","Moy"],
      correctOptionId: 3,
      explanation: "M/S emulsiyasida moy tomchilari suv muhitida tarqalgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_5",
      question: "Suv/moy (S/M) emulsiyasida dispersion muhit nima?",
      options: ["Suv","Gaz","Moy","Qattiq modda"],
      correctOptionId: 2,
      explanation: "S/M holatida suv tomchilari moy ichida tarqalgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_6",
      question: "Emulgatorning asosiy vazifasi nima?",
      options: ["Tomchilarni yiriklashtirish","Sirt tarangligini kamaytirib emulsiyani barqarorlashtirish","Emulsiyani gazga aylantirish","Barcha tomchilarni kristallantirish"],
      correctOptionId: 1,
      explanation: "Emulgator tomchi yuzasida himoya qatlami hosil qilishga yordam beradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_7",
      question: "Emulgator molekulasining gidrofil qismi qaysi fazaga yo'naladi?",
      options: ["Suv fazasiga","Moy fazasiga","Gaz fazasiga","Qattiq cho'kmaga"],
      correctOptionId: 0,
      explanation: "Gidrofob qism esa moy fazasiga yo'naladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_8",
      question: "Ko'pikda dispers faza nima?",
      options: ["Suyuq tomchilar","Qattiq zarrachalar","Molekulyar ionlar","Gaz pufakchalari"],
      correctOptionId: 3,
      explanation: "Gaz pufakchalari suyuq muhitda tarqaladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_9",
      question: "Ko'pik pufakchalarini bir-biridan nima ajratib turadi?",
      options: ["Qattiq kristallar","Yupqa suyuqlik pardalari","Metall elektrodlar","Yarim o'tkazuvchi membrana"],
      correctOptionId: 1,
      explanation: "Gaz pufakchalari yupqa suyuqlik pardalari bilan ajralgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_10",
      question: "Gelning muhim tuzilish belgisi qaysi?",
      options: ["Faqat erkin gaz molekulalari mavjudligi","Barcha zarrachalarning cho'kishi","Dispers fazaning fazoviy to'r hosil qilishi","Molekulalarning to'liq bug'lanishi"],
      correctOptionId: 2,
      explanation: "Fazoviy to'r suyuqlikni o'zida ushlab turadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_11",
      question: "Quyidagilardan qaysi biri gelga misol?",
      options: ["Agar-agar geli","Toza distillangan suv","Quruq havo","Natriy xloridning haqiqiy eritmasi"],
      correctOptionId: 0,
      explanation: "Agar-agar gel slaydda misol sifatida keltirilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_12",
      question: "Liofil sistema uchun qaysi belgi xos?",
      options: ["Dispers faza muhit bilan umuman ta'sirlashmaydi","Elektrolit oz miqdorda qo'shilishi bilanoq doim cho'kadi","Faqat qattiq muhitda hosil bo'ladi","Dispers faza dispersion muhit bilan kuchli ta'sirlashadi"],
      correctOptionId: 3,
      explanation: "Liofil zarrachalar odatda solvat yoki gidrat qavat bilan qoplanadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_13",
      question: "Liofob sistema uchun qaysi belgi xos?",
      options: ["Zarrachalar har doim o'z-o'zidan oson hosil bo'ladi","Dispers faza muhit bilan zaif ta'sirlashadi","Sirt tarangligi mutlaqo nol bo'ladi","Dispers faza faqat gaz bo'ladi"],
      correctOptionId: 1,
      explanation: "Liofob zollar ko'pincha qo'shimcha barqarorlashtirishga muhtoj.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_14",
      question: "Gidrofil zollarning zarrachalari suvda qanday qoplama hosil qiladi?",
      options: ["Quruq tuz kristalini","Gaz pardasini","Gidrat qavatini","Metall qobiqni"],
      correctOptionId: 2,
      explanation: "Suv molekulalari zarrachalarni solvatlaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_15",
      question: "Gidrofob zolning barqarorligi ko'pincha nimaga bog'liq?",
      options: ["Zarrachalar yuzasidagi bir xil ishorali zaryadga","Faqat idish rangiga","Faqat havoning bosimiga","Suvning to'liq bug'lanishiga"],
      correctOptionId: 0,
      explanation: "Bir xil ishorali zaryadli zarrachalar o'zaro itariladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_16",
      question: "Gidrofob zolga elektrolit qo'shilganda qanday jarayon yuz berishi mumkin?",
      options: ["Har doim haqiqiy eritma hosil bo'ladi","Suv avtomatik muzlaydi","Zarrachalar molekulaga aylanadi","Qo'sh elektr qavat siqilib, koagulyatsiya kuchayadi"],
      correctOptionId: 3,
      explanation: "Elektrolit zarrachalar orasidagi elektrostatik itarilishni susaytirishi mumkin.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_17",
      question: "Monodispers sistemada zarrachalar o'lchami qanday?",
      options: ["Juda keng oraliqda farq qiladi","Faqat 1000 nm dan katta","Bir-biriga juda yaqin","Har biri boshqa agregat holatda"],
      correctOptionId: 2,
      explanation: "Monodisperslik — tor o'lcham taqsimoti.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_18",
      question: "Polidispers sistemada zarrachalar o'lchami qanday?",
      options: ["Har doim bir xil","Keng oraliqda farq qiladi","Faqat 1 nm dan kichik","Aniqlab bo'lmaydigan darajada nol"],
      correctOptionId: 1,
      explanation: "Polidispers sistemalarda o'lcham taqsimoti keng.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_19",
      question: "Qaysi zarracha shakli uzun, egiluvchan tolasimon ko'rinishga ega?",
      options: ["Tolali zarracha","Sferik zarracha","Plastinkasimon zarracha","Kubik zarracha"],
      correctOptionId: 0,
      explanation: "Slaydda tolali zarrachalar alohida shakl guruhi sifatida ko'rsatilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_2_20",
      question: "Zarrachalar shakli qaysi xossalarga ta'sir qilishi mumkin?",
      options: ["Faqat idish hajmiga","Faqat moddaning nomiga","Faqat rangning yozilishiga","Oqim, cho'kish va sirt xossalariga"],
      correctOptionId: 3,
      explanation: "Shakl qovushqoqlik, sedimentatsiya va barqarorlikka ta'sir ko'rsatadi.",
      timeLimitSeconds: 20,
    },
  ],
};

export const kk2Quiz3: Quiz = {
  id: "KK2_3",
  title: "Kolloid kimyo — 2-mavzu 3-qism (KK2_3)",
  description: "41–60-savollar: Olinish va tozalash usullari (20s/savol)",
  source: "Bahora Nayimova slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "kk2_3_1",
      question: "Dispers sistemalarni olishning ikki asosiy yo'li qaysi?",
      options: ["Qaynatish va muzlatish","Faqat eritish va bug'latish","Dispersiyalash va kondensatsiya","Filtrlash va sentrifugalash"],
      correctOptionId: 2,
      explanation: "Birinchi yo'lda yirik zarracha maydalanadi, ikkinchisida kichik birliklar birikadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_2",
      question: "Dispersiyalash usulining mohiyati nima?",
      options: ["Yirik zarrachalarni mayda dispers holatgacha maydalash","Kichik ionlarni to'liq yo'qotish","Faqat suyuqlikni bug'latish","Tayyor zolni dializ qilish"],
      correctOptionId: 0,
      explanation: "Mexanik, ultratovush va elektr usullari dispersiyalashga kiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_3",
      question: "Kondensatsiya usulida zarrachalar qanday hosil bo'ladi?",
      options: ["Tayyor zarrachalarni filtrlash orqali","Faqat cho'kmalarni ajratish orqali","Faqat yirik zarrachalarni maydalash orqali","Atom, molekula yoki ionlarning birikishi orqali"],
      correctOptionId: 3,
      explanation: "Kichik birliklardan mayda yangi zarrachalar hosil bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_4",
      question: "Mexanik dispersiyalashda qaysi jihoz qo'llanishi mumkin?",
      options: ["Dializ xaltachasi","Kolloid tegirmon","Yarim o'tkazuvchi parda","Elektr pech"],
      correctOptionId: 1,
      explanation: "Kolloid tegirmon zarrachalarni kuchli siljish ta'sirida maydalaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_5",
      question: "Gomogenizatorning vazifasi nima?",
      options: ["Zarralarni tindirib cho'ktirish","Ionlarni dializ qilish","Tomchilarni mayda holatgacha parchalash","Suyuqlikni kristallantirish"],
      correctOptionId: 2,
      explanation: "Gomogenizator yuqori bosim va tez aralashtirishdan foydalanadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_6",
      question: "Ultratovush bilan dispersiyalashda suyuqlikda qaysi hodisa yuz beradi?",
      options: ["Kavitatsiya pufakchalari hosil bo'ladi","Zarralar faqat muzlaydi","Membrana ionlarni o'tkazadi","Qattiq zarrachalar faqat cho'kadi"],
      correctOptionId: 0,
      explanation: "Pufakchalarning yemirilishi lokal kuchlar hosil qilib zarrachalarni maydalaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_7",
      question: "Elektr usulida dispersiyalash asosan qaysi moddalar zolini olishda ishlatiladi?",
      options: ["Faqat oqsil","Faqat kraxmal","Faqat gazlar","Metalllar"],
      correctOptionId: 3,
      explanation: "Slaydda oltin, kumush va platina zollari ko'rsatilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_8",
      question: "Peptizatsiya nima?",
      options: ["Zolni erituvchisiz quritish","Yangi cho'kmani peptizator bilan kolloid zolga o'tkazish","Zolni membranadan filtrlash","Gazni qattiq moddaga aylantirish"],
      correctOptionId: 1,
      explanation: "Peptizator ionlari cho'kma zarrachalari sirtiga adsorbsiyalanadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_9",
      question: "Peptizatsiyada peptizator ionlari qayerga adsorbsiyalanadi?",
      options: ["Cho'kma zarrachalari sirtiga","Faqat idish devoriga","Faqat gaz fazasiga","Filtr qog'oziga"],
      correctOptionId: 0,
      explanation: "Sirt zaryadlanishi zarrachalarning o'zaro itarilishiga yordam beradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_10",
      question: "Fizik kondensatsiyaga qaysi jarayon misol bo'la oladi?",
      options: ["Yirik zarrachani tegirmonda maydalash","Zolni sentrifugalash","Bug' sovishi natijasida mayda tomchilar hosil bo'lishi","Ionlarni membranadan ajratish"],
      correctOptionId: 2,
      explanation: "Fizik sharoit o'zgarishi tufayli molekulalar birikib zarracha hosil qiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_11",
      question: "Kimyoviy kondensatsiyada zarracha nima natijasida hosil bo'ladi?",
      options: ["Faqat mexanik maydalash","Faqat ultrafiltratsiya","Faqat sentrifugalash","Kimyoviy reaksiya"],
      correctOptionId: 3,
      explanation: "Reaksiya natijasida kam eruvchan mahsulotning mayda zarrachalari hosil bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_12",
      question: "Qaysi jarayon kimyoviy kondensatsiya yo'liga kiradi?",
      options: ["Kolloid tegirmonda maydalash","Gidroliz orqali zol olish","Ultrafiltratsiya","Oddiy tindirish"],
      correctOptionId: 1,
      explanation: "Gidroliz natijasida kam eruvchan gidroksid zarrachalari hosil bo'lishi mumkin.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_13",
      question: "Gidroliz usulida qaysi turdagi zollar olinishi mumkin?",
      options: ["Gidroksid zollari","Faqat gaz aerozollari","Faqat ko'piklar","Faqat haqiqiy eritmalar"],
      correctOptionId: 0,
      explanation: "Slaydda Fe(OH)3 va Al(OH)3 zollari misol qilingan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_14",
      question: "Oksidlanish-qaytarilish orqali zol olishda asosiy hodisa nima?",
      options: ["Membrananing yirtilishi","Qattiq zarrachaning mexanik bo'linishi","Elektron almashinuvi natijasida yangi modda zarrachalarining hosil bo'lishi","Dispers fazaning faqat cho'kishi"],
      correctOptionId: 2,
      explanation: "Yangi moddaning mayda zarrachalari dispersion muhitda hosil bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_15",
      question: "Almashinish reaksiyasi orqali zol hosil qilish uchun qaysi shart muhim?",
      options: ["Hosil bo'lgan modda cheksiz eruvchan bo'lishi","Hech qanday reaksiya sodir bo'lmasligi","Faqat gaz fazasi ishlatilishi","Kam eruvchan mahsulotning mayda zarrachalar holida hosil bo'lishi"],
      correctOptionId: 3,
      explanation: "Tez aralashtirish va sharoit nazorati mayda zarrachalarni saqlashga yordam beradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_16",
      question: "Kolloid zolni tozalashda asosan nimalar ajratib chiqariladi?",
      options: ["Faqat yirik kolloid zarrachalar","Past molekulali ionlar va molekulalar","Faqat dispersion muhitning hammasi","Faqat idish devori"],
      correctOptionId: 1,
      explanation: "Kolloid zarrachalar saqlanib, kichik aralashmalar chiqariladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_17",
      question: "Dializ qaysi vositaga asoslanadi?",
      options: ["Yarim o'tkazuvchan pardadan kichik zarrachalarning o'tishiga","Faqat yuqori tezlikda aylantirishga","Faqat yirik zarrachalarni maydalashga","Faqat yorug'lik sochilishiga"],
      correctOptionId: 0,
      explanation: "Ion va mayda molekulalar diffuziya bilan o'tadi, kolloid zarrachalar ushlanadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_18",
      question: "Elektrodializ dializdan nimasi bilan farq qiladi?",
      options: ["Yarim o'tkazuvchan pardadan foydalanmaydi","Faqat qattiq zarrachalarni maydalaydi","Ionlar ajralishini elektr maydoni bilan tezlashtiradi","Faqat emulsiya hosil qiladi"],
      correctOptionId: 2,
      explanation: "Elektr maydon ionlarni qarama-qarshi elektrodlarga yo'naltiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_19",
      question: "Ultrafiltratsiyada kolloid zarrachalar qayerda ushlanib qoladi?",
      options: ["Gaz fazasida","Elektrod sirtida","Sentrifuga tagida","Maxsus yarim o'tkazuvchan parda yuzasida"],
      correctOptionId: 3,
      explanation: "Parda kichik ion va molekulalarni o'tkazadi, kolloid zarrachalarni ushlaydi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk2_3_20",
      question: "Sentrifugalash komponentlarni qaysi ta'sir bilan ajratadi?",
      options: ["Faqat diffuziya bilan","Markazdan qochma kuch bilan","Faqat yorug'lik bilan","Faqat elektr maydon bilan"],
      correctOptionId: 1,
      explanation: "Aylanishda zarrachalar zichligi va o'lchamiga qarab turlicha ajraladi.",
      timeLimitSeconds: 20,
    },
  ],
};

export const kk2_1Quiz = kk2Quiz1;
export const kk2_2Quiz = kk2Quiz2;
export const kk2_3Quiz = kk2Quiz3;
export const allKk2Quizzes: Quiz[] = [kk2Quiz1, kk2Quiz2, kk2Quiz3];
