import { Quiz } from "./types.js";

/**
 * Kolloid kimyo (KK_M3) — Sirt hodisalari va sirt energiyasi
 * 40 ta savol 2 ta mustaqil quizga bo'lingan: KK3_1, KK3_2
 * Har bir savolga 20 soniya beriladi. Faqat guruhlarda o'tkaziladi.
 * Har safar savollar va 4 ta javob varianti alohida aralashtiriladi.
 */

export const kk3Quiz1: Quiz = {
  id: "KK3_1",
  title: "Kolloid kimyo — 3-mavzu 1-qism (KK3_1)",
  description: "01–20-savollar: Sirt energiyasi va tarangligi (20s/savol)",
  source: "Bahora Nayimova slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "kk3_1_1",
      question: "Sirt hodisalari asosan qayerda kuzatiladi?",
      options: ["Faqat moddaning ichki hajmida","Ikki faza chegarasida","Faqat atom yadrosida","Faqat vakuumda"],
      correctOptionId: 1,
      explanation: "Sirt hodisalari ikki faza chegarasidagi sirt qatlamiga xos.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_2",
      question: "Suyuqlik–gaz chegarasida qaysi hodisa sirt hodisasiga misol bo'ladi?",
      options: ["Tomchi hosil bo'lishi","Yadroviy parchalanish","Kristall panjara hosil bo'lishi","Metallning magnitlanishi"],
      correctOptionId: 0,
      explanation: "Tomchi shakllanishida suyuqlik–gaz chegarasining xossalari muhim.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_3",
      question: "Fazalararo sirt nima?",
      options: ["Faqat qattiq jismning ichki qismi","Ikki fazani ajratib turuvchi chegara qatlami","Har qanday gazning bosimi","Eritmaning umumiy hajmi"],
      correctOptionId: 1,
      explanation: "Fazalararo sirt tarkib yoki holati farqli ikki faza orasidagi chegaradir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_4",
      question: "Sirt qatlami molekulalari hajmiy fazadagilarga nisbatan qanday holatda bo'ladi?",
      options: ["Tortishish kuchlari to'liq muvozanatlangan","Umuman qo'shni molekulalari bo'lmaydi","Tortishish kuchlari muvozanatlanmagan","Potensial energiyasi doim nolga teng"],
      correctOptionId: 2,
      explanation: "Sirt molekulalarining faza tashqarisi tomonidagi qo'shnilari kamroq.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_5",
      question: "Sirt qatlamidagi molekulalarning potensial energiyasi odatda qanday bo'ladi?",
      options: ["Hajmiy fazadagilarnikidan yuqori","Hajmiy fazadagilarnikidan past","Har doim nol","Faqat haroratga teng"],
      correctOptionId: 0,
      explanation: "Muvozanatlanmagan tortishish sirtning ortiqcha energiyasini yuzaga keltiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_6",
      question: "Sirt maydoni S ortsa, boshqa sharoitlar bir xil bo'lganda sirt erkin energiyasi qanday o'zgaradi?",
      options: ["Kamayadi","O'zgarmaydi","Ortadi","Manfiy bo'ladi"],
      correctOptionId: 2,
      explanation: "G^s = σS; σ o'zgarmasa G^s maydonga to'g'ri proporsional.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_7",
      question: "Sirt erkin energiyasining slaydda berilgan ifodasi qaysi?",
      options: ["G^s = σS","G^s = σ/S","G^s = S/σ","G^s = σ + S"],
      correctOptionId: 0,
      explanation: "Sirt erkin energiyasi sirt tarangligi va sirt maydoni ko'paytmasi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_8",
      question: "Sirt maydonini oshirish uchun sarflangan ish qaysi ifoda bilan bog'langan?",
      options: ["A = σΔS","A = σ/ΔS","A = ΔS/σ","A = σ − ΔS"],
      correctOptionId: 0,
      explanation: "Yangi sirt hosil qilish uchun tashqi ish talab etiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_9",
      question: "Nega erkin tomchi sharsimon shaklga intiladi?",
      options: ["Hajmini cheksiz oshirish uchun","Berilgan hajmda sirt maydonini kamaytirish uchun","Zichligini nolga tushirish uchun","Sirt tarangligini har doim oshirish uchun"],
      correctOptionId: 1,
      explanation: "Kichikroq sirt maydoni sirt erkin energiyasini kamaytiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_10",
      question: "Sirt tarangligi fizik jihatdan nimani ifodalaydi?",
      options: ["Suyuqlik massasining hajmga nisbatini","Birlik sirt maydoniga to'g'ri keluvchi sirt erkin energiyasini","Gazning birlik hajmdagi bosimini","Eritmaning elektr o'tkazuvchanligini"],
      correctOptionId: 1,
      explanation: "Berilgan sharoitda σ sirt erkin energiyasining maydon bo'yicha o'zgarishidir.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_11",
      question: "Sirt tarangligining ekvivalent birliklari qaysilar?",
      options: ["N/m va J/m²","N/m² va J/m","kg/m va J/s","mol/L va Pa"],
      correctOptionId: 0,
      explanation: "1 N/m = 1 J/m².",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_12",
      question: "σ = F/l ifodada l nimani bildiradi?",
      options: ["Suyuqlikning hajmini","Chegaraviy chiziq uzunligini","Haroratni","Suyuqlik zichligini"],
      correctOptionId: 1,
      explanation: "F sirt bo'ylab ta'sir etuvchi kuch, l esa chegara uzunligi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_13",
      question: "Sirt tarangligi kattaroq bo'lgan suyuqlikda yangi sirt hosil qilish uchun qanday ish kerak bo'ladi?",
      options: ["Kamroq","Ko'proq","Nolga teng","Faqat gaz bosimiga teng"],
      correctOptionId: 1,
      explanation: "A = σΔS, ya'ni bir xil ΔS uchun σ katta bo'lsa ish ham katta.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_14",
      question: "Stalagmometrik usulda qaysi kattalik kuzatiladi?",
      options: ["Ma'lum hajmdan hosil bo'ladigan tomchilar soni yoki massasi","Suyuqlikning elektr zaryadi","Moddaning spektral chiziqlari","Kristallning qattiqligi"],
      correctOptionId: 0,
      explanation: "Usul tomchi uzilishiga bog'liq kattaliklarga asoslanadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_15",
      question: "Kapillyar ko'tarilish usulida sirt tarangligini baholash uchun qaysi kattalik o'lchanadi?",
      options: ["Eritmaning rangi","Kapillyardagi suyuqlik balandligi","Idishning umumiy massasi","Yorug'lik to'lqin uzunligi"],
      correctOptionId: 1,
      explanation: "Ingichka naychadagi ko'tarilish balandligi h ishlatiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_16",
      question: "Halqa usulida qanday kuch o'lchanadi?",
      options: ["Metall halqani suyuqlik sirtidan uzib olish kuchi","Halqani qizdirish kuchi","Suyuqlikni magnitlash kuchi","Idish tubidagi og'irlik kuchi"],
      correctOptionId: 0,
      explanation: "Halqani sirtdan uzish uchun zarur kuch sirt tarangligiga bog'liq.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_17",
      question: "Plastinka usulida qaysi kuch o'lchanadi?",
      options: ["Suyuqlikka tegib turgan plastinkaga ta'sir etuvchi ho'llanish kuchi","Gazning elektr kuchi","Qattiq jismning elastiklik kuchi","Suyuqlikning magnit kuchi"],
      correctOptionId: 0,
      explanation: "Yupqa plastinka sirt bilan tegishganda unga ho'llanish kuchi ta'sir qiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_18",
      question: "Harorat ortganda ko'pchilik suyuqliklarning sirt tarangligi odatda qanday o'zgaradi?",
      options: ["Ortadi","Kamayadi","Har doim o'zgarmaydi","Darhol cheksiz bo'ladi"],
      correctOptionId: 1,
      explanation: "Harorat ortishi molekulalarning issiqlik harakatini kuchaytiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_19",
      question: "Kritik haroratga yaqinlashganda suyuqlik–bug' sirt tarangligi nimaga yaqinlashadi?",
      options: ["Nolga","Bir molga","Cheksizlikka","Suyuqlik zichligiga"],
      correctOptionId: 0,
      explanation: "Suyuqlik va bug' fazalari orasidagi farq kamayib boradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_1_20",
      question: "Molekulalararo tortishish kuchi kuchliroq bo'lgan suyuqlikda sirt tarangligi odatda qanday bo'ladi?",
      options: ["Pastroq","Yuqoriroq","Har doim nol","Faqat bosimga bog'liq"],
      correctOptionId: 1,
      explanation: "Kuchli koheziya yangi sirt hosil qilish uchun ko'proq energiya talab qiladi.",
      timeLimitSeconds: 20,
    },
  ],
};

export const kk3Quiz2: Quiz = {
  id: "KK3_2",
  title: "Kolloid kimyo — 3-mavzu 2-qism (KK3_2)",
  description: "21–40-savollar: Adsorbsiya, ho'llanish va kapillyarlik (20s/savol)",
  source: "Bahora Nayimova slaydlaridan",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "kk3_2_1",
      question: "Sirt-faol modda konsentratsiyasi ortganda suyuqlik sirt tarangligi odatda qanday o'zgaradi?",
      options: ["Kamayadi","Ortadi","Har doim o'zgarmaydi","Nolga teng zichlikka aylanadi"],
      correctOptionId: 0,
      explanation: "Sirt-faol molekulalar sirtga adsorbsiyalanib σ ni kamaytiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_2",
      question: "Sirt-faol molekuladagi gidrofil qism qaysi fazaga yo'naladi?",
      options: ["Suv fazasiga","Faqat gaz fazasiga","Faqat metall fazasiga","Faqat vakuumga"],
      correctOptionId: 0,
      explanation: "Gidrofil qism suv bilan ta'sirlashishga moyil.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_3",
      question: "Sirt-faol molekuladagi gidrofob qism suv–havo chegarasida odatda qayerga yo'naladi?",
      options: ["Suv hajmining ichkarisiga","Havo tomoniga","Faqat qattiq jism ichiga","Hech qayerga yo'nalmaydi"],
      correctOptionId: 1,
      explanation: "Gidrofob qism suvdan uzoqlashib, havo yoki yog' fazasi tomon joylashadi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_4",
      question: "Sirt-faol modda ma'lum konsentratsiyadan keyin mitsellalar hosil qila boshlaydigan chegara nima deyiladi?",
      options: ["Kritik mitsella konsentratsiyasi","Kritik harorat","Osmotik bosim","Eritma zichligi"],
      correctOptionId: 0,
      explanation: "Slaydda bu chegara KMK bilan belgilangan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_5",
      question: "Gibbs adsorbsiya tenglamasi qaysi ikki o'zgarish orasidagi bog'lanishni ifodalaydi?",
      options: ["Konsentratsiya o'zgarishi va sirt qatlamida to'planish","Bosim va elektr kuchlanishi","Harorat va atom raqami","Hajm va rang"],
      correctOptionId: 0,
      explanation: "Γ sirt ortiqcha adsorbsiyasini, c esa eritma konsentratsiyasini bildiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_6",
      question: "Gibbs tenglamasiga ko'ra dσ/dc < 0 bo'lsa, adsorbsiya belgisi qanday?",
      options: ["Γ > 0","Γ < 0","Γ = 0 bo'lishi shart","Belgini aniqlab bo'lmaydi"],
      correctOptionId: 0,
      explanation: "Γ = −(c/RT)(dσ/dc); musbat c, R va T da hosila manfiy bo'lsa Γ musbat.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_7",
      question: "Musbat adsorbsiya nimani bildiradi?",
      options: ["Modda sirt qatlamida to'planishini","Modda sirt qatlamidan butunlay yo'qolishini","Suyuqlikning qaynashini","Sirt maydonining nol bo'lishini"],
      correctOptionId: 0,
      explanation: "Γ > 0 bo'lganda sirt qatlamidagi miqdor hajmiy fazaga nisbatan ortiqcha.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_8",
      question: "Manfiy adsorbsiya uchun konsentratsiya oshganda sirt tarangligi odatda qanday o'zgaradi?",
      options: ["Ortadi","Kamayadi","Har doim nolga tushadi","Haroratga teng bo'ladi"],
      correctOptionId: 0,
      explanation: "Manfiy adsorbsiyada dσ/dc > 0 deb ko'rsatilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_9",
      question: "Ho'llanish nima?",
      options: ["Suyuqlikning qattiq jism sirtiga tarqalishi yoki u bilan ta'sirlashishi","Suyuqlikning faqat bug'ga aylanishi","Qattiq jismning faqat erishi","Gaz bosimining oshishi"],
      correctOptionId: 0,
      explanation: "Ho'llanish tomchining qattiq sirtda yoyilish darajasi bilan namoyon bo'ladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_10",
      question: "Kontakt burchagi kichik bo'lsa, suyuqlikning qattiq sirtni ho'llashi qanday bo'ladi?",
      options: ["Kuchliroq","Kuchsizroq","Imkonsiz","Burchakka bog'liq emas"],
      correctOptionId: 0,
      explanation: "θ kichraygan sari tomchi sirt bo'ylab ko'proq yoyiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_11",
      question: "Kontakt burchagi θ > 90° bo'lsa, slaydga ko'ra holat qanday?",
      options: ["To'liq ho'llanish","Yaxshi ho'llanish","Yomon ho'llanish","Kapillyar ichida qaynash"],
      correctOptionId: 2,
      explanation: "Katta kontakt burchagi tomchining sferikroq turishiga mos keladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_12",
      question: "Koheziya va adgeziya orasidagi farq qaysi?",
      options: ["Koheziya bir xil, adgeziya turli modda molekulalari orasidagi tortishish","Ikkalasi faqat bir xil molekulalar orasida","Koheziya faqat gaz, adgeziya faqat suyuqlikda","Ikkalasi ham faqat elektr toki bilan bog'liq"],
      correctOptionId: 0,
      explanation: "Koheziya bir xil, adgeziya turli moddalar o'zaro ta'siri.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_13",
      question: "Adgeziya koheziyadan kuchliroq bo'lsa, tomchi qattiq sirtni odatda qanday ho'llaydi?",
      options: ["Kuchli ho'llaydi va yoyiladi","Umuman tegmaydi","Har doim muzlaydi","Faqat bug'lanadi"],
      correctOptionId: 0,
      explanation: "Adgeziyaning ustunligi suyuqlikning sirtda yoyilishini kuchaytiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_14",
      question: "Ho'llovchi suyuqlik ingichka kapillyarda qanday harakatlanadi?",
      options: ["Ko'tariladi","Albatta pastga tushadi","Har doim o'zgarmaydi","Gazga aylanadi"],
      correctOptionId: 0,
      explanation: "Ho'llovchi suyuqlikda θ < 90° va botiq menisk kuzatiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_15",
      question: "Ho'llamaydigan suyuqlik ingichka kapillyarda qanday holat ko'rsatadi?",
      options: ["Sathi pasayadi","Cheksiz ko'tariladi","Rangi doim o'zgaradi","Muzlaydi"],
      correctOptionId: 0,
      explanation: "Ho'llamaydigan suyuqlikda θ > 90° va qavariq menisk kuzatiladi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_16",
      question: "Boshqa kattaliklar bir xil bo'lganda kapillyar radiusi kichrayishi ko'tarilish balandligiga qanday ta'sir qiladi?",
      options: ["Balandlik ortadi","Balandlik kamayadi","Balandlik o'zgarmaydi","Balandlik nol bo'ladi"],
      correctOptionId: 0,
      explanation: "h = 2σcosθ/(ρgr), ya'ni h radiusga teskari proporsional.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_17",
      question: "O'simlik ksilemasida suvning yuqoriga harakatiga yordam beradigan sirt hodisasi qaysi?",
      options: ["Kapillyarlik","Yadroviy parchalanish","Magnit induksiya","Elektroliz"],
      correctOptionId: 0,
      explanation: "Slaydda o'simlik ksilemasi kapillyarlikning tabiiy misoli sifatida berilgan.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_18",
      question: "Emulgator emulsiya tomchilariga qanday ta'sir qiladi?",
      options: ["Chegaraviy sirt tarangligini kamaytirib, birikishga qarshilik ko'rsatadi","Tomchilarni darhol qattiq kristallga aylantiradi","Emulsiyadagi suyuqliklarni bitta sof modda qiladi","Faqat haroratni nolga tushiradi"],
      correctOptionId: 0,
      explanation: "Emulgatorlar tomchi sirtida adsorbsiyalanib emulsiyani barqarorlashtiradi.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_19",
      question: "Ko'pikda qaysi faza pufakchalar shaklida tarqaladi?",
      options: ["Gaz","Qattiq kristall","Suyuq metall","Vakuum"],
      correctOptionId: 0,
      explanation: "Ko'pik — gaz pufakchalari suyuq yoki qattiq muhitda tarqalgan sistema.",
      timeLimitSeconds: 20,
    },
    {
      id: "kk3_2_20",
      question: "Adsorbent va adsorbatning to'g'ri juft ta'rifi qaysi?",
      options: ["Adsorbent — sirtida modda to'planadigan jism; adsorbat — to'planadigan modda","Adsorbent — gazning bosimi; adsorbat — eritmaning hajmi","Adsorbent — faqat suv; adsorbat — faqat havo","Adsorbent — harorat; adsorbat — vaqt"],
      correctOptionId: 0,
      explanation: "Qattiq jism sirtidagi adsorbsiya slaydda shu atamalar bilan berilgan.",
      timeLimitSeconds: 20,
    },
  ],
};

export const allKk3Quizzes: Quiz[] = [kk3Quiz1, kk3Quiz2];
