import { Quiz } from "./types.js";

/**
 * Rus tili va adabiyoti fanidan testlar to'plami (R1 - R6)
 * Har bir quizda 50 tadan savol, har bir savolga 20 soniya vaqt.
 * Barcha quizlar faqat Telegram guruhlarida o'tkaziladi (groupOnly: true)
 * va dinamik ravishda savollar hamda variantlar aralashtiriladi (shuffle: true).
 */

export const russianQuiz1: Quiz = {
  id: "R1",
  title: "Rus tili: 1–50-savollar (R1)",
  description: "Rus tili va adabiyoti bo'yicha 1-qism testlar to'plami (1–50)",
  source: "Rus tilidan testlar 1-kurslar uchun (PDF)",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "r1_1",
      question: "-ая; -яя – окончания какого рода прилагательных?",
      options: ["Женского рода", "Мужского рода", "Среднего рода", "Общего рода"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_2",
      question: "Близкие по значению слова ….",
      options: ["синонимы", "антонимы", "паронимы", "омонимы"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_3",
      question: "В каких годах Самарканд был столицей Узбекистана?",
      options: ["1925-1930", "1933-1938", "1991-1998", "1954-1958"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_4",
      question: "В каком возрасте Ибн Сина стал уже известным среди врачей города?",
      options: ["В 17 лет", "В 19 лет", "В 15 лет", "В 20 лет"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_5",
      question: "В каком году был образован СамГУ?",
      options: ["22 января 1927 года", "4 января 1922 года", "30 декабря 1992 года", "7 сентября 1936 года"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_6",
      question: "В каком году была принята независимость Узбекистана?",
      options: ["В 1991 году", "В 1994 году", "В 1999 году", "В 2003 году"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_7",
      question: "В каком году Ибн Сина пошёл в начальную мусульманскую школу?",
      options: ["В 985 году", "В 986 году", "В 990 году", "В 993 году"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_8",
      question: "В каком году родился Алишер Навои?",
      options: ["В 1441 году", "В 1445 году", "В 1450 году", "В 1442 году"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_9",
      question: "В каком из словосочетаний употреблено одушевленное существительное 3 склонения?",
      options: ["Дикая лошадь", "Белая лилия", "Вечерний город", "Деревянная парта"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_10",
      question: "В каком ряду даны глаголы?",
      options: ["Играла, читал", "Пять, сильный", "Учитель, рано", "Мой, учиться"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_11",
      question: "В начале какого века Улугбек стал правителем Самарканда?",
      options: ["В начале XIY века", "В конце XYII века", "В середине X века", "В XX веке"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_12",
      question: "Вместо точек вставьте нужное местоимение. Это …книга.",
      options: ["моя", "мой", "моё", "мои"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_13",
      question: "Вместо точек вставьте нужное местоимение. Это …семья.",
      options: ["ваша", "ваш", "ваше", "ваши"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_14",
      question: "Вместо точек вставьте нужное местоимение. Это …словарь.",
      options: ["твой", "твоя", "твоё", "твои"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_15",
      question: "Вместо точек вставьте нужную форму глагола. Дети…в школу.",
      options: ["идут", "идёт", "идёте", "идёшь"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_16",
      question: "Вместо точек вставьте нужную форму глагола. Мама …..ужин.",
      options: ["готовила", "готовишь", "готовлю", "готовите"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_17",
      question: "Вместо точек вставьте нужную форму глагола. Мы ….домашнее задание.",
      options: ["выполним", "выполните", "выполняют", "выполнить"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_18",
      question: "Вместо точек вставьте нужную форму глагола. Мы ….журнал.",
      options: ["купили", "купим", "купите", "купишь"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_19",
      question: "Второстепенные члены предложения:",
      options: ["Определение, дополнение, обстоятельство", "Подлежащее, сказуемое", "Определение, подлежащее", "Глагол, обстоятельство"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_20",
      question: "Где и когда родился Имам Аль Бухари?",
      options: ["В Бухаре в 810 году", "В Самарканде в 815 году", "В Ташкенте в 765 году", "В Ургенче в 890 году"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_21",
      question: "Где проводится фестиваль «Шарк тароналари»?",
      options: ["В Самарканде", "В Бухаре", "В Ташкенте", "В Гулистане"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_22",
      question: "Главные члены предложения …",
      options: ["Подлежащее, сказуемое", "Дополнение, обстоятельство", "Определение, сказуемое", "Сказуемое дополнение"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_23",
      question: "Глаголы в предложении чаще всего бывают…",
      options: ["сказуемыми", "дополнением", "определением", "подлежащим"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_24",
      question: "К какому разряду числительных относятся следующие числительные: двое, трое",
      options: ["собирательные", "количественные", "дробные", "порядковые"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_25",
      question: "К какому разряду числительных относятся следующие числительные: первый, третий",
      options: ["порядковые", "собирательные", "количественные", "дробные"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_26",
      question: "К какому склонению относятся слова ведро, поле?",
      options: ["2-склонение", "1-склонение", "3-склонение", "6-склонение"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_27",
      question: "К какому склонению относятся слова день, конь?",
      options: ["2- склонение", "3-склонение", "1-склонение", "4-склонение"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_28",
      question: "К какому склонению относятся слова тетрадь, дверь?",
      options: ["3-склонение", "1-склонение", "2-склонение", "5-склонение"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_29",
      question: "Как называли современники Алишера Навои?",
      options: ["Царь царей стиха", "Наставником учёных", "Великий мыслитель", "Великий энциклопедист"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_30",
      question: "Как переводится выражение «Мой любимый писатель»?",
      options: ["Mening sevimli yozuvchim", "Mening sevimli aktyorim", "Men sevgan olim", "Men sevgan kitob"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_31",
      question: "Как переводится на русский язык «Mening sevimli faslim»?",
      options: ["Моё любимое время года", "Мой любимый писатель", "Моё любимое произведение", "Мой любимый уголок природы"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_32",
      question: "Как переводится словосочетание «животный мир» на узбекский язык?",
      options: ["Hayvonot olami", "O’simlik olami", "Hayvonot bog’i", "Gullar bog’i"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_33",
      question: "Как подчёркивается дополнение?",
      options: ["пунктир", "Пунктир точка", "Волнистая линия", "Прямая линия"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_34",
      question: "Как подчёркивается определение?",
      options: ["Волнистой чертой", "Пунктир точка", "Прямая линия", "пунктир"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_35",
      question: "Какая птица изображена в центре герба?",
      options: ["Птица Хумо", "орёл", "голубь", "ласточка"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_36",
      question: "Какая часть речи обозначает действие предмета?",
      options: ["глагол", "наречие", "местоимение", "Имя числительное"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_37",
      question: "Какая часть речи обозначает количество предмета?",
      options: ["Имя числительное", "глагол", "местоимение", "наречие"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_38",
      question: "Какая часть речи обозначает предмет?",
      options: ["Имя существительное", "глагол", "местоимение", "Имя числительное"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_39",
      question: "Какая часть речи обозначает признак предмета?",
      options: ["Имя прилагательное", "Имя существительное", "глагол", "наречие"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_40",
      question: "Какая часть речи указывает на предметы, но не называет их?",
      options: ["местоимение", "глагол", "Имя существительное", "наречие"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_41",
      question: "Какая часть речи является неизменяемой?",
      options: ["наречие", "глагол", "местоимение", "Имя существительное"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_42",
      question: "Какие древние памятники есть в Самарканде?",
      options: ["Мавзолей Гури Эмир, Биби Ханум", "Ичан Кала, Шахи Зинда", "Ляби Хауз, обсерватория Улугбека", "Ичан Кала, ансамбль Регистан"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_43",
      question: "Какие окончания имеют прилагательные женского рода?",
      options: ["-ая;-яя", "-ый; -ий; -ой", "-ое; -ее", "-яя; ый"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_44",
      question: "Какие окончания имеют прилагательные множественного числа?",
      options: ["-ые; -ие", "-ая; -яя", "-ое; ее", "-ый; яя"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_45",
      question: "Какие окончания имеют прилагательные мужского рода?",
      options: ["-ый;-ой;-ий", "-ая; -яя", "-ое;-ее", "-ый; -яя"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_46",
      question: "Какие окончания имеют прилагательные среднего рода?",
      options: ["-ое; -ее", "-ый; -ий; -ой", "-ая; -яя", "-ий; -ая"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_47",
      question: "Какие окончания имеют существительные женского рода?",
      options: ["-А; -Я;", "Нулевое окончание", "-0; -Е", "Не имеют окончаний"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_48",
      question: "Какие окончания имеют существительные мужского рода?",
      options: ["Нулевое окончание", "-а; я;", "-о; е;", "-ь; -0;"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_49",
      question: "Какие окончания имеют существительные среднего рода?",
      options: ["-о; -е; ё", "-а; -я; -ь", "-й; -ь; -я", "-о; -я; -ь"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r1_50",
      question: "Какие символы имеет республика Узбекистан?",
      options: ["Герб, флаг, гимн", "План, конституция, гимн", "Распорядок, флаг, праздник", "Все ответы верны"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
  ],
};

export const russianQuiz2: Quiz = {
  id: "R2",
  title: "Rus tili: 51–100-savollar (R2)",
  description: "Rus tili va adabiyoti bo'yicha 2-qism testlar to'plami (51–100)",
  source: "Rus tilidan testlar 1-kurslar uchun (PDF)",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "r2_1",
      question: "Какие существительные относятся к первому склонению?",
      options: ["Существительные женского и мужского рода с окончаниями –а;-я.", "Существительные мужского рода с нулевым окончанием", "Существительные среднего рода с окончаниями –о; -е", "Существительные общего рода"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_2",
      question: "Какие существительные относятся к третьему склонению?",
      options: ["Существительные женского рода с мягким знаком", "Существительные мужского рода", "Существительные среднего рода", "Существительные общего рода"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_3",
      question: "Какие существительные относятся ко второму склонению?",
      options: ["Существительные мужского рода с нулевым окончанием, среднего рода с окончаниями –о; -е", "Существительные женского рода с нулевым окончанием", "Существительные только среднего рода", "Существительные только мужского рода"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_4",
      question: "Какие формы времени имеет глагол?",
      options: ["Настоящее время, прошедшее время, будущее время", "Прошедшее время и будущее время", "Настоящее время и повелительное наклонение", "Все ответы верны"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_5",
      question: "Какие цвета есть на флаге Узбекистана?",
      options: ["Красный, белый, синий, зелёный", "Черный, белый, красный, коричневый", "Желтый, зеленый, белый, фиалетовый", "Голубой, желтый, оранжевый"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_6",
      question: "Какие числительные пишутся с мягким знаком в конце?",
      options: ["От 5 до 20, 30", "От 5 до 20", "От 50 до 80", "От 500 до 900"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_7",
      question: "Какие числительные пишутся с мягким знаком в середине слова?",
      options: ["От 50 до 80 От 500 до 900", "От 5 до 20", "От 5 до 20, 30", "От 5 до 100"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_8",
      question: "Какого рода бывают существительные?",
      options: ["Мужского, женского, среднего рода", "Мужского, среднего рода", "Женского, общего рода", "Женского, среднего рода"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_9",
      question: "Какого рода и числа слово “Университет”?",
      options: ["Мужского рода, единственного числа", "Женского рода, множественного числа", "Среднего рода, единственного числа", "Женского рода, единственного числа"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_10",
      question: "Какого рода и числа слово «педагогика»?",
      options: ["Женского рода, единственного числа", "Мужского рода, единственного числа", "Среднего рода, множественного числа", "Общего рода, единственного числа"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_11",
      question: "Какое слово отвечает на вопрос кто?",
      options: ["бухгалтер", "доска", "журнал", "карандаш"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_12",
      question: "Какое слово отвечает на вопрос что?",
      options: ["встреча", "клоун", "волк", "студент"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_13",
      question: "Какой город Самарканд по величине в Узбекистане?",
      options: ["Второй", "первый", "пятый", "шестой"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_14",
      question: "Какой праздник отмечается 1 октября?:",
      options: ["День учителей и наставников", "День Независимости", "День Конституции", "День памяти и почести"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_15",
      question: "Какой праздник отмечается 8 декабря?",
      options: ["День Конституции республики Узбекистан", "День памяти и почести", "День города", "День независимости"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_16",
      question: "Кем был Имам Аль Бухари?",
      options: ["Великий учёный-хадисовед", "Великий астроном", "Великий математик", "Великий поэт"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_17",
      question: "Кем был Улугбек?",
      options: ["Великий учёный математик, астроном", "Великий узбекский поэт", "Великий композитор", "Великий художник"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_18",
      question: "Кем? Чем? вопросы какого падежа?",
      options: ["Творительный падеж", "Предложный падеж", "Винительный падеж", "Именительный падеж"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_19",
      question: "Когда был утвержден герб республики Узбекистан?",
      options: ["2 июля 1992 года", "10 декабря 1993 года", "9 мая 1992 года", "27 августа 1992 года"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_20",
      question: "Когда был утвержден гимн республики Узбекистан?",
      options: ["10 декабря 1992 года", "3 июля 1991 года", "10 января 1995 года", "4 декабря 1996 года"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_21",
      question: "Когда был утвержден Флаг республики Узбекистан?",
      options: ["18 ноября 1991 года", "16 ноября 1992 года", "10 декабря 1994 года", "2 июля 1993 года"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_22",
      question: "Когда была учреждена Красная книга?",
      options: ["В 1948 году", "В 1967 году", "В 1996 году", "В 1992 году"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_23",
      question: "Когда и где проводился фестиваль “Шёлк и специи”?",
      options: ["24-26 мая 2020 года в Бухаре", "18-19 марта в Самарканде", "5-6 мая в Ташкенте", "12-14 августа в Шахрисабзе"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_24",
      question: "Когда и где родился Ибн Сина?",
      options: ["В 980 году в Бухаре", "В 988 году в Самарканде", "В 983 году в Ургенче", "В 987 году в Ташкенте"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_25",
      question: "Когда Ибн Сина становится настоящим учёным энциклопедистом?",
      options: ["В 18 лет", "В 16 лет", "В 19 лет", "В 40 лет"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_26",
      question: "Когда отмечается день города Самарканда?",
      options: ["18 октября", "20 октября", "6 августа", "1 октября"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_27",
      question: "Когда отмечается день Конституции?",
      options: ["8 декабря", "9 февраля", "21 марта", "9 мая"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_28",
      question: "Когда отмечается День Независимости Узбекистана?",
      options: ["1 сентября", "1 октября", "8 декабря", "14 января"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_29",
      question: "Когда родился А.С.Пушкин?",
      options: ["6 июня 1799 года", "10 декабря 1788 года", "22 сентября 1766 года", "21 ноября 1790 года"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_30",
      question: "Кого? Чего? вопросы какого падежа?",
      options: ["Родительный падеж", "Творительный падеж", "Предложный падеж", "Винительный падеж"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_31",
      question: "Кого? Что? вопросы какого падежа?",
      options: ["Винительный падеж", "Именительный падеж", "Родительный падеж", "Дательный падеж"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_32",
      question: "Кому? Чему? вопросы какого падежа?",
      options: ["Дательный падеж", "Именительный падеж", "Родительный падеж", "Творительный падеж"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_33",
      question: "Косвенные падежи это…",
      options: ["Все падежи кроме именительного падежа", "Только винительный падеж", "Только именительный падеж", "Родительный падеж"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_34",
      question: "Кто написал слова гимна?",
      options: ["Абдулла Орипов", "Мутал Бурханов", "Абдулла Каххор", "Уткир Хашимов"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_35",
      question: "Кто сочинил музыку гимна?",
      options: ["Мутал Бурханов", "Абдулла Орипов", "Абдулла Авлоний", "Уткир Хошимов"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_36",
      question: "Кто? Что? вопросы какого падежа?",
      options: ["Именительный падеж", "Винительный падеж", "Творительный падеж", "Родительный падеж"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_37",
      question: "На какие вопросы отвечает винительный падеж?",
      options: ["Кого? Что?", "Кому? Чему?", "О ком? О чём?", "Кого? Чего?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_38",
      question: "На какие вопросы отвечает дательный падеж?",
      options: ["Кому? Чему?", "Кого? Чего?", "Кем? Чем?", "Кто? Что?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_39",
      question: "На какие вопросы отвечает именительный падеж?",
      options: ["Кто? Что?", "Кого? Чего?", "Кому?чему?", "Кого?что?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_40",
      question: "На какие вопросы отвечает предложный падеж?",
      options: ["О ком? Очём?", "Кого? Чего?", "Кому? Чему?", "Кем? Чем?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_41",
      question: "На какие вопросы отвечает родительный падеж?",
      options: ["Кого? Чего?", "Кому? Чему?", "Кем? Чем?", "О ком? О чём?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_42",
      question: "На какие вопросы отвечает творительный падеж?",
      options: ["Кем? Чем?", "Кого? Чего?", "О ком? О чем?", "Кто? Что?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_43",
      question: "На какие вопросы отвечают глаголы настоящего времени?",
      options: ["Что делаю? Что делаем? Что делаете?", "Что делал? Что буду делать? Что делаешь?", "Что сделал? Что делают? Что буду делать?", "Что делала? Что делали? Что сделают?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_44",
      question: "На какие вопросы отвечают глаголы?",
      options: ["Что делать? Что сделать?", "Какой? Чей?", "Кто? Что?", "Сколько? Который?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_45",
      question: "На какие вопросы отвечают имена прилагательные?",
      options: ["Какой? Чей?", "Кто? Что?", "Сколько? Который?", "Что делать? Что сделать?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_46",
      question: "На какие вопросы отвечают имена существительные?",
      options: ["Кто? Что?", "Когда? Где?", "Какой? Чей?", "Как? Каким образом?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_47",
      question: "На какие вопросы отвечают имена числительные?",
      options: ["Сколько? Который?", "Кто? Что?", "Какой?Какая?", "Когда? Где?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_48",
      question: "На какие вопросы отвечают местоимения?",
      options: ["Кто? Чей?", "Что делать? Что сделать?", "Когда? Сколько?", "Где? Куда?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_49",
      question: "На какие вопросы отвечают наречия времени?",
      options: ["Когда? До какого времени?", "Куда? Где?", "Кто? Что?", "Какой? Чей?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r2_50",
      question: "На какие вопросы отвечают наречия места?",
      options: ["Где? Куда? Откуда?", "Когда? Как долго?", "Какой? Чей?", "Как? Каким образом?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
  ],
};

export const russianQuiz3: Quiz = {
  id: "R3",
  title: "Rus tili: 101–150-savollar (R3)",
  description: "Rus tili va adabiyoti bo'yicha 3-qism testlar to'plami (101–150)",
  source: "Rus tilidan testlar 1-kurslar uchun (PDF)",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "r3_1",
      question: "На какие вопросы отвечают прилагательные женского рода?",
      options: ["Какая? Чья?", "Какой? Чей?", "Какое? Чьё?", "Какие? Чьи?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_2",
      question: "На какие вопросы отвечают прилагательные множественного числа?",
      options: ["Какие? Чьи?", "Какая? Чья?", "Какое? Чьё?", "Какой? Чей?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_3",
      question: "На какие вопросы отвечают прилагательные мужского рода?",
      options: ["Какой? Чей?", "Какая? Чья?", "Какое? Чьё?", "Какие? Чьи?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_4",
      question: "На какие вопросы отвечают прилагательные среднего рода?",
      options: ["Какое? чьё?", "Какой? Чей?", "Какая? Чья", "Какие? Чьи?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_5",
      question: "На какой вопрос отвечает неодушевленное существительное?",
      options: ["Что?", "Кто?", "Где?", "Куда?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_6",
      question: "На какой вопрос отвечает несовершенный вид глагола?",
      options: ["Что делать?", "Что сделать?", "Что сделаю?", "Что сделаем?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_7",
      question: "На какой вопрос отвечает одушевлённое существительное?",
      options: ["Кто?", "Что?", "Какой?", "Чей?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_8",
      question: "На какой вопрос отвечает совершенный вид глагола?",
      options: ["Что сделать?", "Что делать?", "Что делал?", "Что делаю?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_9",
      question: "Найдите в данном предложении глагол: Дети играют на улице.",
      options: ["играют", "дети", "улице", "на"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_10",
      question: "Найдите инфинитив",
      options: ["работать", "работаю", "работаете", "работали"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_11",
      question: "Найдите инфинитив",
      options: ["читать", "читал", "читали", "читает"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_12",
      question: "Найдите неодушевлённые существительные",
      options: ["Территория, государство", "Муравей, котёнок", "Юрист, племянник", "Тётя, продавщица"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_13",
      question: "Найдите неодушевленные существительные:",
      options: ["Математика, физика", "Агроном, биолог", "Химик, окулист", "Медицина, филолог"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_14",
      question: "Найдите одушевлённые существительные",
      options: ["Турист, переводчик", "Мавзолей, скамейка", "Памятник, история", "Кафедра, кабинет"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_15",
      question: "Найдите одушевлённые существительные",
      options: ["Тракторист, фермер", "Поезд, билет", "Космос, астроном", "Экономист, рынок"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_16",
      question: "Найдите подлежащее. Мама работает в школе.",
      options: ["мама", "в", "работает", "школе"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_17",
      question: "Найдите подлежащее. Студенты читают интересную книгу.",
      options: ["студенты", "читают", "книгу", "интересную"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_18",
      question: "Найдите правильный перевод слов: здание, праздник, бульвар",
      options: ["Bino,bayram, xiyobon", "Maktab, daraxt, shahar", "Bayram, ko’cha, daftar", "Talaba, bayram, o’qituvchi"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_19",
      question: "Найдите правильный перевод слов: фрукты, воздух, насекомые",
      options: ["Mevalar, havo, hashorotlar", "Osimliklar, mevalar, hashorotlar", "Mevalar, suv, hayvonlar", "Havo, harorat, daraja"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_20",
      question: "Найдите правильный перевод слова словосочетание",
      options: ["So’z birikmasi", "So’z yasovchi", "ega", "kesim"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_21",
      question: "Найдите ряд с неодушевленными существительными",
      options: ["Карандаш, машина, университет", "Собака, сестра, мама", "Художник, врач, мастер", "Папа, лошадь, шкаф"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_22",
      question: "Найдите ряд с неодушевленными существительными",
      options: ["Папка, факультет, улица", "Учитель, художник, врач", "Преподаватель, стол, бабушка", "Доска, повар, мел"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_23",
      question: "Найдите ряд с одушевленными существительными",
      options: ["Моряк, динозавр, студент", "Пальто, город, дом", "Школа, ручка, книга", "Тетрадь, галстук, костюм"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_24",
      question: "Найдите ряд с одушевленными существительными",
      options: ["Лиса, дядя, брат", "Куртка, шкаф, диван", "Телевизор, кухня, стол", "Люстра, волк, погода"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_25",
      question: "Найдите сказуемое. Папа работает врачом в поликлинике.",
      options: ["работает", "врачом", "папа", "поликлинике"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_26",
      question: "Найдите сказуемое. Я учусь в университете.",
      options: ["учусь", "я", "университете", "в"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_27",
      question: "О ком? О чём? вопросы какого падежа?",
      options: ["Предложный падеж", "Дательный падеж", "Именительный падеж", "Родительный падеж"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_28",
      question: "Одинаковые по написанию слова",
      options: ["омонимы", "антонимы", "синонимы", "Все ответы верны"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_29",
      question: "-ое; -ее – окончания какого рода прилагательных?",
      options: ["Среднего рода", "Мужского рода", "Женского рода", "Общего рода"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_30",
      question: "Определите род данных существительных: комната, аудитория, ложка",
      options: ["Женский род", "Мужской род", "Общий род", "Средний род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_31",
      question: "Определите род данных существительных: озеро, растение, облако, имя",
      options: ["Средний род", "Мужской род", "Женский род", "Общий род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_32",
      question: "Определите род данных существительных: платье, время, знамя",
      options: ["Средний род", "Женский род", "Мужской род", "Общий род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_33",
      question: "Определите род данных существительных: прогулка, дочь, история",
      options: ["Женский род", "Мужской род", "Средний род", "Общий род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_34",
      question: "Определите род данных существительных: телевизор, инструктор, подъезд",
      options: ["Мужской род", "Женский род", "Средний род", "Общий род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_35",
      question: "Определите род существительных: ваза, дорога, тетрадь",
      options: ["Женский род", "Мужской род", "Средний род", "Общий род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_36",
      question: "Определите род существительных: здание, имя, море",
      options: ["Средний род", "Мужской род", "Общий род", "Женский род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_37",
      question: "Определите род существительных: климат, гербарий, водопад",
      options: ["Мужской род", "Женский род", "Средний род", "Общий род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_38",
      question: "Определите род существительных: портрет, учитель, санаторий",
      options: ["Мужской род", "Женский род", "Средний род", "Общий род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_39",
      question: "Определите склонение слова упражнение",
      options: ["2 склонение", "1 склонение", "3 склонение", "Общее склонение"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_40",
      question: "Определите склонение существительного дверь",
      options: ["3 склонение", "2 склонение", "1 склонение", "Общее склонение"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_41",
      question: "Определите склонение существительного планета",
      options: ["1 склонение", "2 склонение", "3 склонение", "Общее склонение"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_42",
      question: "Под каким именем известен Ибн Сина в Европе?",
      options: ["Авиценна", "Ибн Сина", "Великий учёный", "Коперник"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_43",
      question: "Подберите антоним к слову «родина»",
      options: ["чужбина", "край", "село", "отчизна"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_44",
      question: "Подберите антоним к слову злой",
      options: ["добрый", "жестокий", "честный", "трудолюбивый"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_45",
      question: "Подберите антонимы к словам добро, утро",
      options: ["Зло, вечер", "День, ночь", "Ум, храбрость", "Сила, воля"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_46",
      question: "Подберите правильно местоимение. …узнаёте это место?",
      options: ["вы", "они", "мы", "я"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_47",
      question: "Подберите правильно местоимение: …учатся в университете.",
      options: ["они", "мы", "вы", "я"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_48",
      question: "Подберите правильно местоимение: Кому …звонишь?",
      options: ["ты", "я", "мы", "они"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_49",
      question: "Подберите правильно местоимение….гуляю в парке.",
      options: ["я", "она", "мы", "вы"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r3_50",
      question: "Подберите синоним к слову маленький",
      options: ["крохотный", "большой", "огромный", "крупный"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
  ],
};

export const russianQuiz4: Quiz = {
  id: "R4",
  title: "Rus tili: 151–200-savollar (R4)",
  description: "Rus tili va adabiyoti bo'yicha 4-qism testlar to'plami (151–200)",
  source: "Rus tilidan testlar 1-kurslar uchun (PDF)",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "r4_1",
      question: "Подберите синоним к слову храбрый",
      options: ["смелый", "умный", "весёлый", "активный"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_2",
      question: "Подберите синонимы к словам большой, веселье",
      options: ["Огромный - радость", "Храбрый- широкий", "Трусливый - маленький", "Злой - радостный"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_3",
      question: "Правильно переведите словосочетание «великие личности»",
      options: ["Buyuk shaxslar", "Buyuk ishlar", "Qadrli insonlar", "Aqlli bola"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_4",
      question: "Правильно подберите существительное к данному прилагательному: железное",
      options: ["здоровье", "характер", "гвоздь", "плита"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_5",
      question: "Правильно подберите существительное к данному прилагательному: цветные",
      options: ["карандаши", "радуга", "бумага", "небо"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_6",
      question: "Правильно подберите существительное к данному прилагательному: честный",
      options: ["человек", "женщина", "студентка", "соседка"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_7",
      question: "Правильно подберите существительное к данному прилагательному:интеллигентная",
      options: ["журналистка", "шофёр", "учитель", "строитель"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_8",
      question: "Правильно подберите числительное к слову блюда:",
      options: ["вторые", "второй", "вторая", "второе"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_9",
      question: "Правильно подберите числительное к слову место:",
      options: ["первое", "первая", "первый", "первые"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_10",
      question: "Правильно подберите числительное к слову ребёнок:",
      options: ["первый", "первая", "первое", "первые"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_11",
      question: "Правильно подберите числительное к слову школа:",
      options: ["пятая", "пятый", "пятое", "пятые"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_12",
      question: "Правильно поставьте глагол в настоящем времени:Я….текст.",
      options: ["читаю", "читает", "читал", "буду читать"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_13",
      question: "Правильно поставьте глагол в прошедшем времени. Мы ….по парку.",
      options: ["гуляли", "гуляю", "гулять", "буду гулять"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_14",
      question: "Правильно поставьте глагол учиться в настоящем времени. Ты….в университете.",
      options: ["учишься", "учится", "учусь", "Буду учиться"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_15",
      question: "Правильно поставьте глагол. Мама …. в Ташкенте.",
      options: ["родилась", "родился", "родились", "родилось"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_16",
      question: "Правильно поставьте окончание в винительном падеже: Я люблю свою (страна).",
      options: ["Я люблю свою страну.", "Я люблю свою страна.", "Я люблю свою страной.", "Я люблю свою страны."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_17",
      question: "Противоположные по значению слова…",
      options: ["антонимы", "омонимы", "синонимы", "паронимы"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_18",
      question: "Сколько букв в русском алфавите?",
      options: ["33", "28", "30", "31"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_19",
      question: "Сколько видов рыб обитает в водах Сырдарьи и Амударьи?",
      options: ["60 видов рыб", "40 видов рыб", "100 видов рыб", "70 видов рыб"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_20",
      question: "Сколько гласных букв в русском алфавите?",
      options: ["10", "7", "8", "5"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_21",
      question: "Сколько звезд изображено на флаге республики Узбекистан?",
      options: ["12", "10", "9", "7"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_22",
      question: "Сколько звезд указано в таблице Мирзо Улугбека?",
      options: ["1018 звезд", "1020 звезд", "1037 звезд", "1024 звезд"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_23",
      question: "Сколько падежей есть в русском языке?",
      options: ["6", "5", "4", "2"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_24",
      question: "Сколько самостоятельных частей речи?",
      options: ["6", "5", "4", "2"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_25",
      question: "Сколько склонений имеют имена существительные?",
      options: ["3 склонения", "2 склонения", "1 склонение", "Все ответы верны"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_26",
      question: "Сколько согласных букв в русском алфавите?",
      options: ["21", "24", "16", "20"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_27",
      question: "Сколько спряжений имеет глагол?",
      options: ["2", "3", "4", "5"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_28",
      question: "Сколько хадисов включает в себя произведение Имама Аль Бухари «Аль Джамеа ас Сахих»?",
      options: ["Около 7300", "Около 5500", "Около 6700", "Около 7020"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_29",
      question: "Сколько хадисов знал наизусть Аль Бухари в 14-15 лет?",
      options: ["80-90 тысяч", "50-60 тысяч", "70-80 тысяч", "40-50 тысяч"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_30",
      question: "Существительные бывают…",
      options: ["Единственного и множественного числа", "Только единственного числа", "Только множественного числа", "Общего числа"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_31",
      question: "Существительные в предложении чаще всего бывают",
      options: ["подлежащими", "сказуемыми", "дополнением", "определением"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_32",
      question: "Существительные какого рода относятся к 3 склонению?",
      options: ["Женского рода", "Мужского рода", "Среднего рода", "Общего рода"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_33",
      question: "Укажите антонимы",
      options: ["Трудолюбивый - ленивый", "Весёлый - радостный", "Добрый - вежливый", "Сильный - храбрый"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_34",
      question: "Укажите будущее простое время глагола",
      options: ["прочитаю", "Буду рисовать", "Хочу играть", "Могу работать"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_35",
      question: "Укажите будущее сложное время глагола",
      options: ["Буду заниматься", "нарисую", "прочитаю", "напишу"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_36",
      question: "Укажите великих мыслителей Востока",
      options: ["Беруни, Ибн Сина, Улугбек", "Коперник, Джордано Бруно, Навои", "Джами, Эйнштейн, Ньютон", "Джордано Бруно, Амир Темур, Ньютон"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_37",
      question: "Укажите вопросительное предложение",
      options: ["Кто сегодня отсутствует?", "Какая чудесная погода!", "Сегодня будет собрание.", "Студенты сегодня посетили музей."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_38",
      question: "Укажите время выделенного глагола. Завтра я прочитаю произведение Пушкина.",
      options: ["Будущее время", "Настоящее время", "Прошедшее время", "Определенное время"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_39",
      question: "Укажите время выделенного глагола. Мама купила продукты.",
      options: ["Прошедшее время", "Настоящее время", "Будущее простое время", "Будущее сложное время"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_40",
      question: "Укажите время выделенного глагола. Она разговаривает по телефону.",
      options: ["Настоящее время", "Прошедшее время", "Будущее простое время", "Будущее сложное время"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_41",
      question: "Укажите количественные числительные",
      options: ["Сорок, три, шестьдесят", "Двое, трое, четверо", "Первый, второй, пятый", "Одна десятая, три, четвертый"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_42",
      question: "Укажите личные местоимения",
      options: ["Я, ты, он, она, мы, вы, они", "Мой, твой, наш, ваш", "Кто, что, каждый", "Себе, себя"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_43",
      question: "Укажите многозначное слово",
      options: ["ручка", "снег", "город", "телефон"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_44",
      question: "Укажите многозначное слово:",
      options: ["лист", "дождь", "зима", "Самарканд"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_45",
      question: "Укажите наречие",
      options: ["хорошо", "красивый", "всегда", "четыре"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_46",
      question: "Укажите наречия времени",
      options: ["Сегодня , завтра", "Здесь, там", "Весело, хорошо", "Плохо, грустно"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_47",
      question: "Укажите неправильное словосочетание",
      options: ["Умный девочка", "Одарённый студент", "Аккуратный ребёнок", "Добросовестный человек"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_48",
      question: "Укажите однозначное слово",
      options: ["весна", "кисть", "ручка", "лист"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_49",
      question: "Укажите однозначное слово:",
      options: ["тетрадь", "лист", "рука", "кисть"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r4_50",
      question: "Укажите омонимы",
      options: ["Лук (стрела) – лук (овощ)", "Огромный - большой", "Сильный - храбрый", "Грусть - радость"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
  ],
};

export const russianQuiz5: Quiz = {
  id: "R5",
  title: "Rus tili: 201–250-savollar (R5)",
  description: "Rus tili va adabiyoti bo'yicha 5-qism testlar to'plami (201–250)",
  source: "Rus tilidan testlar 1-kurslar uchun (PDF)",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "r5_1",
      question: "Укажите повествовательное предложение.",
      options: ["Наступила холодная зима.", "Где ты учишься?", "Ура, у нас каникулы!", "Кто сегодня отсутствует?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_2",
      question: "Укажите порядковые числительные",
      options: ["Второй, десятый, двадцатый", "Пять, пятьдесят, сто", "Двое, трое, пятеро", "Сорок, третий, тысяча"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_3",
      question: "Укажите правильное написание словосочетания 20 занятие",
      options: ["Двадцатое занятие", "Двадцатая занятие", "Двадцатый занятие", "Двадцатые занятие"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_4",
      question: "Укажите правильное написание числительного 23:",
      options: ["Двадцать три", "Двенадцать три", "Двадцать третий", "Двадцат три"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_5",
      question: "Укажите правильное словосочетание",
      options: ["Талантливая актриса", "Трудолюбивый мама", "Строгая папа", "Ленивый девочка"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_6",
      question: "Укажите правильное словосочетание",
      options: ["Первый этаж", "Второй квартира", "Третья подъезд", "Вторая дом"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_7",
      question: "Укажите правильное словосочетание:",
      options: ["Новый телефон", "Новая телефон", "Новое телефон", "Новые телефон"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_8",
      question: "Укажите правильные окончания: интересн..книга, верн..друг, глубок..озеро",
      options: ["-ая; -ый; -ое", "-ые; -ая; -ее", "-яя; -ое; -ый", "-ий; -ее; -ая"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_9",
      question: "Укажите правильные окончания: перв..упражнение, втор..этаж, книжн..полка",
      options: ["-ое; -ой; -ая", "-ая; -ое; -ий", "-яя; -ее; -ие", "-ий; ая; -ое"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_10",
      question: "Укажите правильный вариант",
      options: ["В моей семье 4 человека.", "В моей семье 4 человек.", "В моей семье 4 человеком.", "В моей семье 4 человеков."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_11",
      question: "Укажите правильный вариант. Сегодня мы … к лекции.",
      options: ["готовимся", "готовлю", "готовите", "готовишься"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_12",
      question: "Укажите правильный ответ вопроса: Что делают студенты на занятии?",
      options: ["Студенты слушают лекцию и пишут конспект.", "Студенты играли футбол на стадионе.", "Студенты готовились к экзамену.", "Студенты будут готовиться к празднику."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_13",
      question: "Укажите правильный ответ на вопрос: Сколько тебе лет?",
      options: ["Мне 20 лет.", "Мне 19 год.", "Мне 21 года.", "Мне 22 лет."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_14",
      question: "Укажите правильный ответ. Где ты живёшь?",
      options: ["Я живу в Самарканде.", "Я живёт в Самарканде.", "Я живёшь в Самарканде.", "Я жил в Самарканде."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_15",
      question: "Укажите правильный перевод вопроса: Какие фрукты созревают осенью?",
      options: ["Kuzda qanaqa mevalar pishadi?", "Kuzda qanaqa sabzavotlar yetiladi?", "Kuzda qanaqa bayramlar nishonlanadi?", "Kuzda qaysi bayramlar nishonlanadi?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_16",
      question: "Укажите правильный перевод названия праздника: День памяти и почести",
      options: ["Xotira va qadrlash kuni", "Til bayrami", "Konstitutsiya kuni", "Mustaqillik kuni"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_17",
      question: "Укажите правильный перевод пословицы: Друг познается в беде.",
      options: ["Do’st kulfatda bilinadi.", "Do’st o’qishda bilinadi.", "Do’st har doim yordam beradi.", "Do’st bilan obod uying."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_18",
      question: "Укажите правильный перевод предложения: Men har kuni kutubxonada shug’ullanaman.",
      options: ["Я каждый день занимаюсь в библиотеке.", "Я каждый день занимаюсь спортом.", "Я каждень день делаю уроки.", "В библиотеке много книг."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_19",
      question: "Укажите правильный перевод предложения: Mening otam 42 yoshda.",
      options: ["Моему отцу 42 года.", "Моему отцу 42 лет.", "Моему оцу 42 год.", "Моей отцу 42 год."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_20",
      question: "Укажите правильный перевод предложения: Mening yoshim 18 da.",
      options: ["Мне 18 лет.", "Мне 18 год.", "Мне 18 года.", "Моей 18 год."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_21",
      question: "Укажите правильный перевод слов природа, пустыня, оазис, равнина",
      options: ["Tabiat, cho’l, voha, tekislik", "O’rmon, dasht, voha, o’simlik", "Daryo, tabiat, hayvon, meva", "Yomg’ir,cho’l, voha, o’rmon"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_22",
      question: "Укажите правильный перевод слов создать, отдел",
      options: ["Yaratmoq, bo’lim", "Kutmoq, nusxa", "Chiqmoq, kitob", "Uxlamoq, xona"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_23",
      question: "Укажите правильный перевод слова «дискуссия»",
      options: ["Bahs-munozara", "tadqiqot", "taqdimot", "izlanuvchi"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_24",
      question: "Укажите правильный перевод словосочетания “государственный деятель”.",
      options: ["Davlat arbobi", "Davlat fuqarosi", "Taniqli olim", "Mashxur izlanuvchi"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_25",
      question: "Укажите правильный перевод словосочетания «Mehnatsevar inson»",
      options: ["Трудолюбивый человек", "Добрый человек", "Умный человек", "Великодушный человек"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_26",
      question: "Укажите правильный перевод словосочетания «богатое наследие»",
      options: ["Boy meros", "Boy inson", "Boy tassurot", "Boy mazmun"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_27",
      question: "Укажите правильный перевод словосочетания «государственный деятель»",
      options: ["Davlat arbobi", "Davlat rahbari", "Davlat xizmatchisi", "Davlat ishi"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_28",
      question: "Укажите правильный перевод словосочетания: Мой распорядок дня.",
      options: ["Mening kun tartibim", "Mening dars jadvalim.", "Mening oilam.", "Mening rejalarim."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_29",
      question: "Укажите прилагательное",
      options: ["пасмурная", "погода", "солнце", "солнечно"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_30",
      question: "Укажите притяжательные местоимения",
      options: ["Мой, твой, наш, ваш", "Я, ты, он, мы, вы", "Всякий, каждый", "Себя, кто-то"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_31",
      question: "Укажите простое будущее время глагола",
      options: ["Студент прочитает книгу.", "Учитель будет объяснять тему.", "Студент может подготовить доклад.", "Они будут готовиться к празднику Независимости."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_32",
      question: "Укажите простые числительные:",
      options: ["Один, три, четыре", "Тридцать четыре, пятьдесят пять, девяносто", "Сорок семь, шесть, три десятых", "Шестьдесят, шестьдеят семь, сто восемь"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_33",
      question: "Укажите род данного словосочетания: вкусная еда",
      options: ["Женский род", "Мужской род", "Средний род", "Общий род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_34",
      question: "Укажите род данного словосочетания: интересное занятие",
      options: ["Средний род", "Общий род", "Мужской род", "Женский род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_35",
      question: "Укажите род данного словосочетания: одарённый студент",
      options: ["Мужской род", "Женский род", "Средний род", "Общий род"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_36",
      question: "Укажите род и число слова «герой»",
      options: ["Мужской род, единственное число", "Женский род, множественное число", "Средний род, единственное число", "Общий род, множественное число"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_37",
      question: "Укажите русских писателей и поэтов",
      options: ["А.С.Пушкин, Лермонтов, Гоголь", "Некрасов, А.Навои, Гёте", "Ибн Сина, З.М.Бабур", "Чехов, Э.Вахидов"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_38",
      question: "Укажите ряд антонимов",
      options: ["Богатый- бедный", "Большой -громадный", "Маленький - мелкий", "Красивый- прекрасный"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_39",
      question: "Укажите ряд местоимений",
      options: ["Я, мой, себя", "Говорить, твой, природа", "Мы, слушать, село", "Идти, новый, пчела"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_40",
      question: "Укажите ряд неодушевлённых существительных",
      options: ["Сообщение, пенал, лекция", "Монтёр, строитель, слон", "Ученик, мастер, шофёр", "Профессор, сестра, птица"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_41",
      question: "Укажите ряд одушевлённых существительных",
      options: ["Медведь, снегурочка, инженер", "Зонтик, деревня, костёр", "Мясо, кухня, повар", "Пчела, сообщение, лекция"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_42",
      question: "Укажите ряд прилагательных",
      options: ["Высокий, интересный, добрый", "Высоко, петь, красный", "Край, мастер, первый", "Злой, четыре, университет"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_43",
      question: "Укажите ряд с глаголами прошедшего времени",
      options: ["Написал, читала, играли", "Пишу, читаю, слушаю", "Прочитаю, нарисую, буду писать", "Играешь, танцуешь, говорит"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_44",
      question: "Укажите ряд с переносным значеним",
      options: ["Хмурый вечер", "Хмурый человек", "Золотые серьги", "Черные туфли"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_45",
      question: "Укажите ряд с прямым значением слова.",
      options: ["Тёмная ночь", "Тёмное прошлое", "Золотое сердце", "Тяжёлая жизнь"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_46",
      question: "Укажите ряд синонимов",
      options: ["Родина, отчизна, отечество", "Край, чужбина, деревня", "Храбрость, доброта, умение", "Нужда, злость, учёба"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_47",
      question: "Укажите ряд существительных",
      options: ["Учитель, журнал, книга", "Говорил, красный, дом", "Огромный, два, человек", "Завтра, школа, писать"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_48",
      question: "Укажите ряд существительных женского рода:",
      options: ["парта, родина, земля", "дядя, город, дерево", "дедушка, санаторий, зерно", "павлин, карта, сочинение"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_49",
      question: "Укажите ряд существительных мужского рода:",
      options: ["рельс, дядя, журнал", "мама, окно, дверь", "море, яблоко, задание", "знамя, машина, ручка"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r5_50",
      question: "Укажите ряд существительных среднего рода:",
      options: ["Растение, платье, время", "Дневник, юбка, юноша", "Мужчина, окно, жизнь", "Автомобиль, дочь, море"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
  ],
};

export const russianQuiz6: Quiz = {
  id: "R6",
  title: "Rus tili: 251–300-savollar (R6)",
  description: "Rus tili va adabiyoti bo'yicha 6-qism testlar to'plami (251–300)",
  source: "Rus tilidan testlar 1-kurslar uchun (PDF)",
  groupOnly: true,
  shuffle: true,
  questions: [
    {
      id: "r6_1",
      question: "Укажите ряд числительных",
      options: ["Два, тридцать, сто", "Огромный, озеро, рано", "Всегда, мой, каждый", "Факультет, четыре, твой"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_2",
      question: "Укажите синонимы",
      options: ["Печальный - грустный", "Весёлый- грустный", "Большой- маленький", "Трудолюбивый - ленивый"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_3",
      question: "Укажите словосочетание женского рода",
      options: ["Новая школа", "Глубокое озеро", "Умные студенты", "большой дом"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_4",
      question: "Укажите словосочетание множественного числа",
      options: ["Добрые люди", "Милая девочка", "Холодный ветер", "Красивое платье"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_5",
      question: "Укажите словосочетание мужского рода:",
      options: ["Престижный университет", "Новая квартира", "Высокое здание", "Лучшие друзья"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_6",
      question: "Укажите словосочетание с переносным значением",
      options: ["Тяжёлый характер", "Золотые серьги", "Воет волк", "Холодный край"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_7",
      question: "Укажите словосочетание с прямым значением",
      options: ["Кислое яблоко", "Кислое лицо", "Тяжёлый характер", "Золотые руки"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_8",
      question: "Укажите словосочетание среднего рода",
      options: ["Черное море", "Красивая сумка", "тёплое пальто", "Верные друзья"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_9",
      question: "Укажите сложное будущее время глагола.",
      options: ["Я буду рисовать картину.", "Художник нарисует картину.", "Студент напишет сочинение.", "Студент отвечает новую тему."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_10",
      question: "Укажите сложное числительное",
      options: ["пятьдесят", "четыре", "Сорок семь", "Сто два"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_11",
      question: "Укажите составное числительное",
      options: ["Тридцать четыре", "сорок", "семьдесят", "пятьдесят"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_12",
      question: "Укажите существительное",
      options: ["характер", "плохо", "ленивый", "доброжелательный"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_13",
      question: "Укажите существительные 1-склонения",
      options: ["Дядя, доска, аудитория", "Конь, осень, дерево", "Студент, коридор, земля", "Планета, природа, день"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_14",
      question: "Укажите существительные 2-склонения",
      options: ["Факультет, зерно, учитель", "Парта, дверь, рубашка", "Сила, юноша, растение", "Море, дядя, мама"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_15",
      question: "Укажите существительные 3-склонения",
      options: ["Жизнь, осень, тетрадь", "Машина, улица, здание", "Памятник, конференция, конь", "Озеро, пальто, люстра"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_16",
      question: "Укажите существительные единственного числа",
      options: ["Сочинение, письмо, сообщение", "Руки, книги, очки", "Часы, город, дома", "Кроссовки, краска, ножницы"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_17",
      question: "Укажите существительные женского рода",
      options: ["Морковь, ваза, радость", "Шампунь, рубашка, темя", "Озеро, конь, змея", "Равнина, пустыня, дельфин"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_18",
      question: "Укажите существительные множественного числа",
      options: ["Каникулы, брюки", "Слово, учебник", "Факультет, предмет", "Утро, вечер"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_19",
      question: "Укажите существительные множественного числа",
      options: ["Носки, часы, ботинки", "Кофта, журнал, улица", "Фонарь, фонтан, земля", "Почва, небо, облако"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_20",
      question: "Укажите существительные мужского рода",
      options: ["Автомобиль, вечер, дядя", "Трава, молодость, свежесть", "Зерно, племя, семя", "Пенал, пламя, игра"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_21",
      question: "Укажите существительные среднего рода",
      options: ["Государство, задание, солнце", "Дорога, село, путь", "Антенна, конспект, институт", "Тема, объявление, конверт"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_22",
      question: "Укажите числительное",
      options: ["Пятьдесят пять", "трудная", "храбрый", "несколько"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_23",
      question: "Укажите числительное, в конце которого пишется мягкий знак",
      options: ["Восемнадцат..", "Сорок…", "Пятьдесят…", "Девяносто…"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_24",
      question: "Укажите число данного прилагательного: талантливые дети",
      options: ["Множественное число", "Единственное число", "Определенное число", "Общее число"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_25",
      question: "Укажите время данных глаголов: играли, плавали, занимались",
      options: ["Прошедшее время", "Настоящее время", "Будущее время", "Общее время"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_26",
      question: "Что изучает морфология?",
      options: ["Части речи", "Часть слова", "Звуки речи", "Значение слов"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_27",
      question: "Что изучает фонетика?",
      options: ["Звуки речи", "буквы", "Части речи", "Значение слов"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_28",
      question: "Что обозначает глагол?",
      options: ["Действие предмета", "Количество предмета", "Признак предмета", "предмет"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_29",
      question: "Что обозначает имя прилагательное?",
      options: ["Признак предмета", "предмет", "Количество предмета", "Действие предмета"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_30",
      question: "Что обозначает имя существительное?",
      options: ["предмет", "Действие предмета", "Количество предмета", "Признак предмета"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_31",
      question: "Что обозначает имя числительное?",
      options: ["Количество и порядок предметов", "Признак предмета", "Действие предмета", "предмет"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_32",
      question: "Что означает слово «экология»?",
      options: ["Oikos -дом, logos-наука", "Oikos –природа, logos-охрана", "Oikos – родной, logos-край", "Oikos – наука, logos-природа"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_33",
      question: "Что такое автобиография?",
      options: ["Описание своей жизни", "Описание характера человека", "Описание внешности человека", "Описание способностей человека"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_34",
      question: "Что такое антонимы?",
      options: ["Это слова с противоположными значениями", "Это близкие по значению слова", "Это одинаковые по написанию слова", "Это слова с переносным значением"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_35",
      question: "Что такое инфинитив?",
      options: ["Начальная форма глагола", "Настоящее время глагола", "Прошедшее время глагола", "Будущее время глагола"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_36",
      question: "Что такое местоимение?",
      options: ["Самостоятельная часть речи, которая указывает на предметы, но не называет их", "Самостоятельная часть речи, которая обозначает действие", "Самостоятельная часть речи, которая обозначает предмет", "Самостоятельная часть речи, которая обозначает признак предмета"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_37",
      question: "Что такое многозначные слова?",
      options: ["Слова, которые имеют два или более лексических значений", "имеют одно лексическое значение", "имеют прямое значение", "имеют переносное значение"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_38",
      question: "Что такое наречие?",
      options: ["Неизменяемая самостоятельная часть речи", "Часть предложения", "Главный член предложения", "Второстепенный член предложения"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_39",
      question: "Что такое общежитие?",
      options: ["Это место временного проживания для студентов.", "Это постоянное место жительства студентов.", "Это место для проведения занятий.", "Это место для отдыха."],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_40",
      question: "Что такое однозначное слово?",
      options: ["Слово, которое имеет одно лексическое значение", "Слово, которое имеет несколько значений", "Слово с прямым значением", "Слова, которые имеют переносное значение"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_41",
      question: "Что такое омонимы?",
      options: ["Это слова одинаковые по звучанию и написанию, но разные по значению", "Это слова с противоположными значениями", "Это слова близкие по значению", "Это слова с переносным значением"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_42",
      question: "Что такое подлежащее?",
      options: ["Главный член предложения", "Часть речи", "Второстепенный член предложения", "Часть слова"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_43",
      question: "Что такое синонимы?",
      options: ["Это близкие по значению, разные по написанию слова", "Это слова с противоположными значениями", "Это слова одинаковые по написанию", "Это слова с прямым значением"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_44",
      question: "Что такое сказуемое?",
      options: ["Главный член предложения", "Часть речи", "Часть слова", "Второстепенный член предложения"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_45",
      question: "Что такое ударение?",
      options: ["Произношение одного из слогов с большей силой", "Оно устанавливает правила написания слов", "Изучает разделение слов на слоги", "Изучает звуки речи"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_46",
      question: "-ые; -ие – окончания какого числа прилагательных?",
      options: ["Множественного числа", "Единственного числа", "Общего числа", "Все ответы верны"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_47",
      question: "-ый; -ий; -ой – окончания какого рода прилагательных?",
      options: ["Мужского рода", "Женского рода", "Среднего рода", "Общего рода"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_48",
      question: "Я забыла, как ……этот фильм",
      options: ["называется", "зовут", "назвать", "название"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_49",
      question: "Укажите повествовательное предложение.",
      options: ["Наступила холодная зима.", "Где ты учишься?", "Ура, у нас каникулы!", "Кто сегодня отсутствует?"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
    {
      id: "r6_50",
      question: "Укажите порядковые числительные",
      options: ["Второй, десятый, двадцатый", "Пять, пятьдесят, сто", "Двое, трое, пятеро", "Сорок, третий, тысяча"],
      correctOptionId: 0,
      timeLimitSeconds: 20,
    },
  ],
};

export const allRussianQuizzes: Quiz[] = [
  russianQuiz1,
  russianQuiz2,
  russianQuiz3,
  russianQuiz4,
  russianQuiz5,
  russianQuiz6,
];
